/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MinimalismUIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  macSidebar: false,
  hideTabBar: false,
  disablePinTab: true,
  simplifyPanel: false,
  disableNoteTabs: false,
  noteStyle: false,
  homePage: ""
};
var FileSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor() {
    super(...arguments);
    this.onPickCb = null;
  }
  onPick(cb) {
    this.onPickCb = cb;
    return this;
  }
  getSuggestions(query) {
    return this.app.vault.getMarkdownFiles().filter((f) => f.path.toLowerCase().includes(query.toLowerCase())).slice(0, 20);
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    var _a;
    this.setValue(file.path);
    (_a = this.onPickCb) == null ? void 0 : _a.call(this, file.path);
    this.close();
  }
};
var MinimalismUIPlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.pinBlockHandler = null;
    this.detachPatches = /* @__PURE__ */ new Map();
    this.tabLimitHandler = null;
    this.dragBar = null;
    this.dragBarTitleHandler = null;
    this.dragBarLayoutHandler = null;
    this.statusBarOriginalParent = null;
    this.statusBarOriginalNextSibling = null;
    this.homePageHandler = null;
    this.isOpeningHomePage = false;
    this.loadedFonts = [];
  }
  async onload() {
    await this.loadSettings();
    await this.loadJetBrainsMono();
    await this.loadSourceHanSansSC();
    this.applyBodyClasses();
    this.applyPinBlock();
    this.applyTabLimit();
    this.app.workspace.onLayoutReady(() => {
      this.applyDragBar();
      this.applyHomePage();
      this.openHomePage();
    });
    this.addSettingTab(new MinimalismUISettingTab(this.app, this));
  }
  onunload() {
    document.body.classList.remove(
      "minimalism-ui-mac-sidebar",
      "minimalism-ui-hide-tab-bar",
      "minimalism-ui-disable-pin",
      "minimalism-ui-simplify-panel",
      "minimalism-ui-disable-note-tabs",
      "minimalism-ui-note-style"
    );
    for (const font of this.loadedFonts)
      document.fonts.delete(font);
    this.loadedFonts = [];
    this.removePinBlockHandler();
    this.removeTabLimitHandler();
    this.removeDragBar();
    this.removeHomePageHandler();
  }
  fontPath(filename) {
    const adapter = this.app.vault.adapter;
    return adapter.getResourcePath(`${this.manifest.dir}/fonts/${filename}`);
  }
  async loadFontFace(family, descriptors) {
    const { file, ...desc } = descriptors;
    const face = new FontFace(family, `url('${this.fontPath(file)}')`, desc);
    try {
      await face.load();
      document.fonts.add(face);
      this.loadedFonts.push(face);
    } catch (e) {
    }
  }
  async loadJetBrainsMono() {
    await Promise.all([
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Regular.ttf", style: "normal", weight: "400" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Italic.ttf", style: "italic", weight: "400" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Medium.ttf", style: "normal", weight: "500" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-MediumItalic.ttf", style: "italic", weight: "500" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Bold.ttf", style: "normal", weight: "700" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-BoldItalic.ttf", style: "italic", weight: "700" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-ExtraBold.ttf", style: "normal", weight: "900" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-ExtraBoldItalic.ttf", style: "italic", weight: "900" })
    ]);
  }
  async loadSourceHanSansSC() {
    const unicodeRange = "U+4E00-9FA5, U+9FA6-9FFF, U+3400-4DBF, U+2E80-2EF3, U+2F00-2FD5, U+2FF0-2FFB, U+3007, U+31C0-31E3, U+3105-312F, U+31A0-31BA, U+F900-FAD9, U+2F800-2FA1D";
    await Promise.all([
      this.loadFontFace("SourceHanSansSC", { file: "SourceHanSansSC-Light.otf", weight: "300", unicodeRange }),
      this.loadFontFace("SourceHanSansSC", { file: "SourceHanSansSC-Regular.otf", weight: "normal", unicodeRange }),
      this.loadFontFace("SourceHanSansSC", { file: "SourceHanSansSC-Medium.otf", weight: "500", unicodeRange }),
      this.loadFontFace("SourceHanSansSC", { file: "SourceHanSansSC-Bold.otf", weight: "bold", unicodeRange }),
      this.loadFontFace("SourceHanSansSC", { file: "SourceHanSansSC-Heavy.otf", weight: "900", unicodeRange })
    ]);
  }
  applyBodyClasses() {
    const cls = document.body.classList;
    cls.toggle("minimalism-ui-mac-sidebar", this.settings.macSidebar);
    cls.toggle("minimalism-ui-hide-tab-bar", this.settings.hideTabBar);
    cls.toggle("minimalism-ui-disable-pin", this.settings.disablePinTab);
    cls.toggle("minimalism-ui-simplify-panel", this.settings.simplifyPanel);
    cls.toggle("minimalism-ui-disable-note-tabs", this.settings.disableNoteTabs);
    cls.toggle("minimalism-ui-note-style", this.settings.noteStyle);
  }
  applyPinBlock() {
    this.removePinBlockHandler();
    if (!this.settings.disablePinTab)
      return;
    this.pinBlockHandler = (e) => {
      if (e.target.closest(".workspace-tab-header.tappable")) {
        e.stopImmediatePropagation();
        e.preventDefault();
      }
    };
    document.addEventListener("contextmenu", this.pinBlockHandler, true);
    this.patchSidebarLeafDetach();
  }
  applyTabLimit() {
    this.removeTabLimitHandler();
    if (!this.settings.disableNoteTabs)
      return;
    this.tabLimitHandler = () => {
      const rootLeaves = [];
      this.app.workspace.iterateRootLeaves((leaf) => {
        rootLeaves.push(leaf);
      });
      if (rootLeaves.length <= 1)
        return;
      const active = this.app.workspace.activeLeaf;
      for (const leaf of rootLeaves) {
        if (leaf !== active)
          leaf.detach();
      }
    };
    this.app.workspace.on("layout-change", this.tabLimitHandler);
  }
  applyDragBar() {
    this.removeDragBar();
    if (!this.settings.disableNoteTabs)
      return;
    const rootEl = this.app.workspace.rootSplit.containerEl;
    const tabsEl = rootEl.querySelector(".workspace-tabs");
    if (!tabsEl)
      return;
    this.dragBar = document.createElement("div");
    this.dragBar.className = "minimalism-ui-drag-bar";
    const titleEl = document.createElement("span");
    titleEl.className = "minimalism-ui-drag-bar-title";
    this.dragBar.appendChild(titleEl);
    tabsEl.insertBefore(this.dragBar, tabsEl.firstChild);
    const updateTitle = () => {
      const activeFile = this.app.workspace.getActiveFile();
      titleEl.textContent = activeFile ? activeFile.basename : "";
    };
    updateTitle();
    this.dragBarTitleHandler = updateTitle;
    this.app.workspace.on("active-leaf-change", updateTitle);
    this.dragBarLayoutHandler = () => {
      if (!this.dragBar || this.dragBar.isConnected)
        return;
      const rootEl2 = this.app.workspace.rootSplit.containerEl;
      const tabsEl2 = rootEl2.querySelector(".workspace-tabs");
      if (tabsEl2)
        tabsEl2.insertBefore(this.dragBar, tabsEl2.firstChild);
    };
    this.app.workspace.on("layout-change", this.dragBarLayoutHandler);
    const statusBar = document.querySelector(".status-bar");
    if (statusBar) {
      this.statusBarOriginalParent = statusBar.parentElement;
      this.statusBarOriginalNextSibling = statusBar.nextElementSibling;
      this.dragBar.appendChild(statusBar);
    }
  }
  applyHomePage() {
    this.removeHomePageHandler();
    if (!this.settings.homePage)
      return;
    this.homePageHandler = (file) => {
      if (!file)
        this.openHomePage();
    };
    this.app.workspace.on("file-open", this.homePageHandler);
  }
  async openHomePage() {
    if (this.isOpeningHomePage)
      return;
    const path = this.settings.homePage;
    if (!path)
      return;
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile))
      return;
    this.isOpeningHomePage = true;
    try {
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
    } finally {
      this.isOpeningHomePage = false;
    }
  }
  removeDragBar() {
    if (this.dragBarTitleHandler) {
      this.app.workspace.off("active-leaf-change", this.dragBarTitleHandler);
      this.dragBarTitleHandler = null;
    }
    if (this.dragBarLayoutHandler) {
      this.app.workspace.off("layout-change", this.dragBarLayoutHandler);
      this.dragBarLayoutHandler = null;
    }
    if (this.statusBarOriginalParent) {
      const statusBar = document.querySelector(".status-bar");
      if (statusBar) {
        if (this.statusBarOriginalNextSibling) {
          this.statusBarOriginalParent.insertBefore(statusBar, this.statusBarOriginalNextSibling);
        } else {
          this.statusBarOriginalParent.appendChild(statusBar);
        }
      }
      this.statusBarOriginalParent = null;
      this.statusBarOriginalNextSibling = null;
    }
    if (this.dragBar) {
      this.dragBar.remove();
      this.dragBar = null;
    }
  }
  removeTabLimitHandler() {
    if (this.tabLimitHandler) {
      this.app.workspace.off("layout-change", this.tabLimitHandler);
      this.tabLimitHandler = null;
    }
  }
  removeHomePageHandler() {
    if (this.homePageHandler) {
      this.app.workspace.off("file-open", this.homePageHandler);
      this.homePageHandler = null;
    }
  }
  patchSidebarLeafDetach() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (this.detachPatches.has(leaf))
        return;
      const leafEl = leaf.containerEl;
      if (!(leafEl == null ? void 0 : leafEl.closest(".workspace-split.mod-left-split")))
        return;
      const original = leaf.detach.bind(leaf);
      leaf.detach = () => {
      };
      this.detachPatches.set(leaf, original);
    });
  }
  removePinBlockHandler() {
    if (this.pinBlockHandler) {
      document.removeEventListener("contextmenu", this.pinBlockHandler, true);
      this.pinBlockHandler = null;
    }
    for (const [leaf, original] of this.detachPatches) {
      leaf.detach = original;
    }
    this.detachPatches.clear();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyBodyClasses();
    this.applyPinBlock();
    this.applyTabLimit();
    this.applyDragBar();
    this.applyHomePage();
  }
};
var MinimalismUISettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h3", { text: "\u5916\u89C2\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u6781\u7B80\u4FA7\u8FB9\u680F").setDesc("\u4E3A\u5DE6\u4FA7\u8FB9\u680F\u5E94\u7528\u78E8\u7802\u73BB\u7483\u80CC\u666F\u3001\u5706\u89D2\u9AD8\u4EAE\u7B49 Finder \u89C6\u89C9\u6548\u679C").addToggle((t) => t.setValue(this.plugin.settings.macSidebar).onChange(async (v) => {
      this.plugin.settings.macSidebar = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6781\u7B80\u5BFC\u822A\u680F").setDesc("\u9690\u85CF\u7B14\u8BB0\u533A\u57DF\u9876\u90E8\u7684\u6807\u7B7E\u680F\uFF0C\u9650\u5236\u540C\u65F6\u53EA\u80FD\u6253\u5F00\u4E00\u4E2A\u7B14\u8BB0\uFF0C\u5E76\u7981\u7528 Pin \u529F\u80FD").addToggle((t) => t.setValue(this.plugin.settings.disableNoteTabs).onChange(async (v) => {
      this.plugin.settings.disableNoteTabs = v;
      this.plugin.settings.disablePinTab = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6781\u7B80\u4FE1\u606F\u680F").setDesc("\u9690\u85CF\u5DE6\u4FA7\u5C5E\u6027\u680F\u7684\u64CD\u4F5C\u6309\u94AE\uFF0C\u4EE5\u53CA Outline\u3001Backlinks \u9762\u677F\u4E2D\u7684\u641C\u7D22\u6846").addToggle((t) => t.setValue(this.plugin.settings.hideTabBar).onChange(async (v) => {
      this.plugin.settings.hideTabBar = v;
      this.plugin.settings.simplifyPanel = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u7B14\u8BB0\u6837\u5F0F").setDesc("\u4FEE\u6539\u7B14\u8BB0\u90E8\u5206\u4E3B\u9898\u6837\u5F0F").addToggle((t) => t.setValue(this.plugin.settings.noteStyle).onChange(async (v) => {
      this.plugin.settings.noteStyle = v;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u4EA4\u4E92\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u7B14\u8BB0\u9996\u9875").setDesc("\u8BBE\u7F6E\u4E00\u4E2A\u7B14\u8BB0\u4F5C\u4E3A\u9996\u9875\u3002Obsidian \u542F\u52A8\u65F6\u81EA\u52A8\u6253\u5F00\uFF0C\u5173\u95ED\u6240\u6709\u6807\u7B7E\u540E\u81EA\u52A8\u8FD4\u56DE\u3002").addText((text) => {
      text.setPlaceholder("\u8F93\u5165\u7B14\u8BB0\u8DEF\u5F84\uFF0C\u4F8B\u5982\uFF1Asrc/Home.md").setValue(this.plugin.settings.homePage);
      new FileSuggest(this.app, text.inputEl).onPick(async (path) => {
        this.plugin.settings.homePage = path;
        await this.plugin.saveSettings();
      });
      text.inputEl.addEventListener("change", async () => {
        this.plugin.settings.homePage = text.inputEl.value.trim();
        await this.plugin.saveSettings();
      });
    });
  }
};
