/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MinimalismUIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  macSidebar: false,
  showProperties: true,
  showLocalGraph: false,
  hideTabBar: false,
  disablePinTab: true,
  simplifyPanel: false,
  disableNoteTabs: false,
  enableLeafCache: false,
  enableNavAnimation: false,
  noteStyle: false,
  homePage: "",
  filenamePrefixLength: 0,
  showBreadcrumb: false,
  language: "auto"
};

// src/TabCacheManager.ts
var import_obsidian = require("obsidian");
var TabCacheManager = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
    this.leafQueue = [];
    this.isReusingLeaf = false;
    this.isEvicting = false;
    this.originalGetLeaf = null;
    // 导航历史存储文件路径，与 leaf 生命周期完全解耦
    this.navHistory = [];
    this.navFuture = [];
    // 当前正在执行的后退/前进目标路径，用于阻止 navTrackHandler 将该激活记录为新导航
    this.navJumpPath = null;
    this.tabLimitHandler = null;
    this.navTrackHandler = null;
    this.navAnimateHandler = null;
    this.pendingAnimationCls = null;
    // tab 关闭后 Obsidian 自动激活下一个 leaf 会触发 active-leaf-change，该标志阻止其被记录为新导航
    this._isClosingTab = false;
    this.navTimer = null;
    this.animEndListeners = /* @__PURE__ */ new WeakMap();
    this.resizeObserverErrHandler = null;
    this.historyPatches = /* @__PURE__ */ new Map();
    // root leaf detach 补丁：触发时设置 _isClosingTab，覆盖所有关闭路径（CMD+W、右键、X 按钮）
    this.rootDetachPatches = /* @__PURE__ */ new Map();
    this.origGoBack = null;
    this.origGoForward = null;
    // 由 getLeaf patch 新建、尚未调用 openFile 的空 leaf
    this.pendingInterceptLeaves = /* @__PURE__ */ new Set();
    // 首页打开期间为 true，避免 getLeaf 拦截器介入
    this._isOpeningHomePage = false;
    // 侧边栏 leaf 的 detach 拦截（pin guard），key=leaf，value=原始 detach
    this.sidebarDetachPatches = /* @__PURE__ */ new Map();
    this.sidebarLayoutChangeHandler = null;
    this.renameHandler = null;
  }
  apply() {
    var _a, _b;
    this.remove();
    this.leafQueue = [];
    this.resizeObserverErrHandler = (e) => {
      if (e.message === "ResizeObserver loop completed with undelivered notifications.") {
        e.stopImmediatePropagation();
        e.preventDefault();
      }
    };
    window.addEventListener("error", this.resizeObserverErrHandler, true);
    if (!this.getSettings().disableNoteTabs) return;
    const ws = this.app.workspace;
    this.originalGetLeaf = ws.getLeaf.bind(ws);
    ws.getLeaf = (newLeaf) => {
      const shouldIntercept = newLeaf === false || newLeaf === void 0 || newLeaf === true || newLeaf === "tab";
      if (shouldIntercept && !this.isReusingLeaf && !this._isOpeningHomePage) {
        const leaf = this.originalGetLeaf("tab");
        this.interceptLeafOpenFile(leaf);
        return leaf;
      }
      return this.originalGetLeaf(newLeaf);
    };
    this.tabLimitHandler = () => {
      if (this.isEvicting) return;
      const active = this.app.workspace.getMostRecentLeaf();
      if (!active) return;
      this.leafQueue = this.leafQueue.filter((l) => l !== active);
      this.leafQueue.push(active);
      const rootLeaves = [];
      this.app.workspace.iterateRootLeaves((l) => rootLeaves.push(l));
      this.leafQueue = this.leafQueue.filter((l) => rootLeaves.includes(l));
      const max = 30;
      if (this.leafQueue.length > max) {
        this.isEvicting = true;
        try {
          while (this.leafQueue.length > max) {
            this.leafQueue.shift().detach();
          }
        } finally {
          this.isEvicting = false;
        }
      }
    };
    this.app.workspace.on("active-leaf-change", this.tabLimitHandler);
    this.navTrackHandler = (leaf) => {
      var _a2, _b2;
      if (!leaf) return;
      let isRootLeaf = false;
      this.app.workspace.iterateRootLeaves((l) => {
        if (l === leaf) isRootLeaf = true;
      });
      if (!isRootLeaf) return;
      const filePath = (_b2 = (_a2 = leaf.view) == null ? void 0 : _a2.file) == null ? void 0 : _b2.path;
      if (!filePath) return;
      if (this.navJumpPath !== null && filePath === this.navJumpPath) {
        this.navJumpPath = null;
        this._isClosingTab = false;
        return;
      }
      if (this._isClosingTab) {
        this._isClosingTab = false;
        return;
      }
      const last = this.navHistory[this.navHistory.length - 1];
      if (last === filePath) return;
      this.navHistory.push(filePath);
      this.navFuture = [];
    };
    this.app.workspace.on("active-leaf-change", this.navTrackHandler);
    this.navAnimateHandler = (leaf) => {
      if (!this.pendingAnimationCls || !leaf) return;
      const cls = this.pendingAnimationCls;
      this.pendingAnimationCls = null;
      if (!this.getSettings().enableNavAnimation) return;
      requestAnimationFrame(() => {
        var _a2;
        const el = (_a2 = leaf.view) == null ? void 0 : _a2.contentEl;
        if (!el) return;
        el.classList.remove("minimalism-ui-slide-from-left", "minimalism-ui-slide-from-right");
        requestAnimationFrame(() => {
          const oldListener = this.animEndListeners.get(el);
          if (oldListener) el.removeEventListener("animationend", oldListener);
          const listener = () => el.classList.remove(cls);
          el.addEventListener("animationend", listener, { once: true });
          this.animEndListeners.set(el, listener);
          el.classList.add(cls);
        });
      });
    };
    this.app.workspace.on("active-leaf-change", this.navAnimateHandler);
    this.app.workspace.iterateRootLeaves((leaf) => {
      this.patchLeafHistory(leaf);
      this.patchRootLeafDetach(leaf);
      this.leafQueue.push(leaf);
    });
    const mostRecent = this.app.workspace.getMostRecentLeaf();
    if (mostRecent) {
      this.leafQueue = this.leafQueue.filter((l) => l !== mostRecent);
      this.leafQueue.push(mostRecent);
      if (this.navHistory.length === 0) {
        const seedPath = (_b = (_a = mostRecent.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path;
        if (seedPath) this.navHistory.push(seedPath);
      }
    }
    const appCmds = this.app.commands.commands;
    const backCmd = appCmds["app:go-back"];
    const fwdCmd = appCmds["app:go-forward"];
    if (backCmd) {
      this.origGoBack = { callback: backCmd.callback, checkCallback: backCmd.checkCallback };
      delete backCmd.callback;
      backCmd.checkCallback = (checking) => {
        if (checking) return this.navHistory.length >= 2;
        this.navigateBack();
        return true;
      };
    }
    if (fwdCmd) {
      this.origGoForward = { callback: fwdCmd.callback, checkCallback: fwdCmd.checkCallback };
      delete fwdCmd.callback;
      fwdCmd.checkCallback = (checking) => {
        if (checking) return this.navFuture.length > 0;
        this.navigateForward();
        return true;
      };
    }
    this.renameHandler = (file, oldPath) => {
      if (!(file instanceof import_obsidian.TFile)) return;
      const newPath = file.path;
      this.navHistory = this.navHistory.map((p) => p === oldPath ? newPath : p);
      this.navFuture = this.navFuture.map((p) => p === oldPath ? newPath : p);
      if (this.navJumpPath === oldPath) this.navJumpPath = newPath;
    };
    this.app.vault.on("rename", this.renameHandler);
    if (this.getSettings().disablePinTab) {
      this.patchSidebarLeafDetach();
      this.sidebarLayoutChangeHandler = () => this.patchSidebarLeafDetach();
      this.app.workspace.on("layout-change", this.sidebarLayoutChangeHandler);
    }
  }
  remove() {
    if (this.originalGetLeaf) {
      this.app.workspace.getLeaf = this.originalGetLeaf;
      this.originalGetLeaf = null;
    }
    if (this.tabLimitHandler) {
      this.app.workspace.off("active-leaf-change", this.tabLimitHandler);
      this.tabLimitHandler = null;
    }
    if (this.navTrackHandler) {
      this.app.workspace.off("active-leaf-change", this.navTrackHandler);
      this.navTrackHandler = null;
    }
    if (this.navAnimateHandler) {
      this.app.workspace.off("active-leaf-change", this.navAnimateHandler);
      this.navAnimateHandler = null;
    }
    this.pendingAnimationCls = null;
    this._isClosingTab = false;
    if (this.navTimer !== null) {
      activeWindow.clearTimeout(this.navTimer);
      this.navTimer = null;
    }
    if (this.resizeObserverErrHandler) {
      window.removeEventListener("error", this.resizeObserverErrHandler, true);
      this.resizeObserverErrHandler = null;
    }
    this.unpatchAllLeafHistories();
    this.unpatchAllRootLeafDetaches();
    const appCmds = this.app.commands.commands;
    if (this.origGoBack) {
      const cmd = appCmds["app:go-back"];
      if (cmd) {
        delete cmd.checkCallback;
        if (this.origGoBack.callback) cmd.callback = this.origGoBack.callback;
        if (this.origGoBack.checkCallback) cmd.checkCallback = this.origGoBack.checkCallback;
      }
      this.origGoBack = null;
    }
    if (this.origGoForward) {
      const cmd = appCmds["app:go-forward"];
      if (cmd) {
        delete cmd.checkCallback;
        if (this.origGoForward.callback) cmd.callback = this.origGoForward.callback;
        if (this.origGoForward.checkCallback) cmd.checkCallback = this.origGoForward.checkCallback;
      }
      this.origGoForward = null;
    }
    if (this.sidebarLayoutChangeHandler) {
      this.app.workspace.off("layout-change", this.sidebarLayoutChangeHandler);
      this.sidebarLayoutChangeHandler = null;
    }
    if (this.renameHandler) {
      this.app.vault.off("rename", this.renameHandler);
      this.renameHandler = null;
    }
    for (const [leaf, original] of this.sidebarDetachPatches) {
      leaf.detach = original;
    }
    this.sidebarDetachPatches.clear();
    this.leafQueue = [];
    this.navJumpPath = null;
    this.pendingInterceptLeaves.clear();
  }
  // 检查指定 leaf 是否正处于等待 openFile 的 pending 状态
  // 供外部（homePageHandler）判断：若为 pending 则不应触发首页跳转
  hasPendingIntercept(leaf) {
    return this.pendingInterceptLeaves.has(leaf);
  }
  getNavHistory() {
    return this.navHistory;
  }
  // 对新建的空 leaf 注入一次性 openFile 拦截器：
  // 在文件实际加载前检查缓存，若已有相同文件的 leaf 则直接复用，避免闪烁
  interceptLeafOpenFile(leaf) {
    if (!leaf.parent) return;
    this.pendingInterceptLeaves.add(leaf);
    const origOpenFile = leaf.openFile.bind(leaf);
    leaf.openFile = async (file, state) => {
      leaf.openFile = origOpenFile;
      this.pendingInterceptLeaves.delete(leaf);
      if (!this.isReusingLeaf) {
        let existingLeaf = null;
        this.app.workspace.iterateRootLeaves((l) => {
          var _a, _b;
          if (existingLeaf || l === leaf) return;
          if (((_b = (_a = l.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === file.path) {
            existingLeaf = l;
          }
        });
        if (existingLeaf) {
          this.isReusingLeaf = true;
          try {
            this.leafQueue = this.leafQueue.filter((l) => l !== existingLeaf);
            this.leafQueue.push(existingLeaf);
            this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
            leaf.detach();
          } finally {
            this.isReusingLeaf = false;
          }
          return;
        }
      }
      this.patchLeafHistory(leaf);
      this.patchRootLeafDetach(leaf);
      const result = await origOpenFile(file, state);
      if (leaf.parent) {
        this.addToNavHistory(file.path);
      }
      return result;
    };
  }
  // 将文件路径写入 navHistory（幂等：已是末尾则跳过，同时清除 forward 历史）
  addToNavHistory(filePath) {
    const last = this.navHistory[this.navHistory.length - 1];
    if (last === filePath) return;
    this.navHistory.push(filePath);
    this.navFuture = [];
  }
  navigateBack() {
    if (this.navTimer !== null) {
      activeWindow.clearTimeout(this.navTimer);
      this.navTimer = null;
    }
    while (this.navHistory.length >= 2) {
      const prevPath = this.navHistory[this.navHistory.length - 2];
      const file = this.app.vault.getAbstractFileByPath(prevPath);
      if (!(file instanceof import_obsidian.TFile)) {
        this.navHistory.splice(this.navHistory.length - 2, 1);
        continue;
      }
      const current = this.navHistory.pop();
      this.navFuture.unshift(current);
      let targetLeaf = null;
      this.app.workspace.iterateRootLeaves((l) => {
        var _a, _b;
        if (!targetLeaf && ((_b = (_a = l.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === prevPath) targetLeaf = l;
      });
      this.navJumpPath = prevPath;
      this.pendingAnimationCls = "minimalism-ui-slide-from-left";
      if (targetLeaf) {
        const leaf = targetLeaf;
        this.navTimer = activeWindow.setTimeout(() => {
          this.navTimer = null;
          this.app.workspace.setActiveLeaf(leaf, { focus: true });
        }, 0);
      } else {
        this.navTimer = activeWindow.setTimeout(async () => {
          this.navTimer = null;
          const newLeaf = this.originalGetLeaf("tab");
          this.patchLeafHistory(newLeaf);
          this.patchRootLeafDetach(newLeaf);
          await newLeaf.openFile(file);
          this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
        }, 0);
      }
      return;
    }
  }
  navigateForward() {
    if (this.navTimer !== null) {
      activeWindow.clearTimeout(this.navTimer);
      this.navTimer = null;
    }
    while (this.navFuture.length > 0) {
      const nextPath = this.navFuture.shift();
      const file = this.app.vault.getAbstractFileByPath(nextPath);
      if (!(file instanceof import_obsidian.TFile)) continue;
      this.navHistory.push(nextPath);
      let targetLeaf = null;
      this.app.workspace.iterateRootLeaves((l) => {
        var _a, _b;
        if (!targetLeaf && ((_b = (_a = l.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === nextPath) targetLeaf = l;
      });
      this.navJumpPath = nextPath;
      this.pendingAnimationCls = "minimalism-ui-slide-from-right";
      if (targetLeaf) {
        const leaf = targetLeaf;
        this.navTimer = activeWindow.setTimeout(() => {
          this.navTimer = null;
          this.app.workspace.setActiveLeaf(leaf, { focus: true });
        }, 0);
      } else {
        this.navTimer = activeWindow.setTimeout(async () => {
          this.navTimer = null;
          const newLeaf = this.originalGetLeaf("tab");
          this.patchLeafHistory(newLeaf);
          this.patchRootLeafDetach(newLeaf);
          await newLeaf.openFile(file);
          this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
        }, 0);
      }
      return;
    }
  }
  patchLeafHistory(leaf) {
    var _a, _b;
    const history = leaf.history;
    if (!history || this.historyPatches.has(leaf)) return;
    const origBack = history.back.bind(history);
    const origForward = history.forward.bind(history);
    const origCanGoBack = (_a = history.canGoBack) == null ? void 0 : _a.bind(history);
    const origCanGoForward = (_b = history.canGoForward) == null ? void 0 : _b.bind(history);
    history.back = () => this.navigateBack();
    history.forward = () => this.navigateForward();
    history.canGoBack = () => this.navHistory.length >= 2;
    history.canGoForward = () => this.navFuture.length > 0;
    this.historyPatches.set(leaf, { back: origBack, forward: origForward, canGoBack: origCanGoBack, canGoForward: origCanGoForward });
  }
  unpatchAllLeafHistories() {
    for (const [leaf, orig] of this.historyPatches) {
      const history = leaf.history;
      if (history) {
        history.back = orig.back;
        history.forward = orig.forward;
        if (orig.canGoBack !== void 0) history.canGoBack = orig.canGoBack;
        if (orig.canGoForward !== void 0) history.canGoForward = orig.canGoForward;
      }
    }
    this.historyPatches.clear();
  }
  // root leaf detach 补丁：通过捕获所有关闭路径（CMD+W、右键、X 按钮、API 调用）
  // 在 detach 前执行两件事：
  //   1. 从 navHistory 移除该文件路径的最后一次出现，使历史指针与实际位置保持一致
  //   2. 设置 _isClosingTab，阻止 navTrackHandler 将关闭后的自动激活记录为新导航
  // isReusingLeaf / isEvicting 为 true 时豁免：属于插件内部操作而非用户关闭 tab
  // navFuture 不修改：关闭 tab 不影响前进历史，已关闭的文件路径仍可通过前进重新打开
  patchRootLeafDetach(leaf) {
    if (this.rootDetachPatches.has(leaf)) return;
    const original = leaf.detach.bind(leaf);
    leaf.detach = () => {
      var _a, _b;
      if (!this.isReusingLeaf && !this.isEvicting) {
        const closingPath = (_b = (_a = leaf.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path;
        if (closingPath) {
          const idx = this.navHistory.lastIndexOf(closingPath);
          if (idx !== -1) this.navHistory.splice(idx, 1);
        }
        this._isClosingTab = true;
        const prevPath = this.navHistory[this.navHistory.length - 1];
        if (prevPath) {
          this.navJumpPath = prevPath;
          if (this.navTimer !== null) {
            activeWindow.clearTimeout(this.navTimer);
            this.navTimer = null;
          }
          this.navTimer = activeWindow.setTimeout(async () => {
            this.navTimer = null;
            let targetLeaf = null;
            this.app.workspace.iterateRootLeaves((l) => {
              var _a2, _b2;
              if (!targetLeaf && ((_b2 = (_a2 = l.view) == null ? void 0 : _a2.file) == null ? void 0 : _b2.path) === prevPath) targetLeaf = l;
            });
            if (targetLeaf) {
              this.app.workspace.setActiveLeaf(targetLeaf, { focus: true });
            } else if (this.originalGetLeaf) {
              const file = this.app.vault.getAbstractFileByPath(prevPath);
              if (file instanceof import_obsidian.TFile) {
                const newLeaf = this.originalGetLeaf("tab");
                this.patchLeafHistory(newLeaf);
                this.patchRootLeafDetach(newLeaf);
                await newLeaf.openFile(file);
                this.app.workspace.setActiveLeaf(newLeaf, { focus: true });
              }
            }
          }, 0);
        }
      }
      original();
    };
    this.rootDetachPatches.set(leaf, original);
  }
  unpatchAllRootLeafDetaches() {
    for (const [leaf, original] of this.rootDetachPatches) {
      leaf.detach = original;
    }
    this.rootDetachPatches.clear();
  }
  // 拦截左侧边栏所有 leaf 的 detach，防止用户通过右键菜单关闭（pin guard）
  patchSidebarLeafDetach() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (this.sidebarDetachPatches.has(leaf)) return;
      const leafEl = leaf.containerEl;
      if (!(leafEl == null ? void 0 : leafEl.closest(".workspace-split.mod-left-split"))) return;
      const original = leaf.detach.bind(leaf);
      leaf.detach = () => {
      };
      this.sidebarDetachPatches.set(leaf, original);
    });
  }
  // 绕过 patchSidebarLeafDetach 的阻断，强制 detach 一个 leaf（供 SidebarLayoutManager 调用）
  forceDetachLeaf(leaf) {
    const original = this.sidebarDetachPatches.get(leaf);
    if (original) {
      original();
    } else {
      leaf.detach();
    }
  }
  // 打开首页笔记：先置 _isOpeningHomePage 防止 getLeaf 拦截器介入，再补 history / detach patch
  async openHomePage() {
    if (this._isOpeningHomePage) return;
    const path = this.getSettings().homePage;
    if (!path) return;
    if (activeDocument.querySelector(".modal-container")) return;
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile)) return;
    this._isOpeningHomePage = true;
    try {
      const leaf = this.app.workspace.getLeaf(false);
      let existingLeaf = null;
      this.app.workspace.iterateRootLeaves((l) => {
        var _a, _b;
        if (existingLeaf || l === leaf) return;
        if (((_b = (_a = l.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === file.path) existingLeaf = l;
      });
      if (existingLeaf) {
        this.leafQueue = this.leafQueue.filter((l) => l !== existingLeaf);
        this.leafQueue.push(existingLeaf);
        this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
        leaf.detach();
        return;
      }
      await leaf.openFile(file);
      this.patchLeafHistory(leaf);
      this.patchRootLeafDetach(leaf);
    } finally {
      this._isOpeningHomePage = false;
    }
  }
};

// src/DragBarManager.ts
var import_obsidian2 = require("obsidian");

// src/utils.ts
var LeafNameUtils = class {
  static stripPrefix(name, prefixLength) {
    if (prefixLength <= 0) return name;
    if (name.length + 1 > prefixLength) return name.slice(prefixLength);
    return name;
  }
};

// src/DragBarManager.ts
var COMPACT_THRESHOLD = 15;
var DragBarManager = class {
  constructor(app, getSettings, navHistoryGetter = () => []) {
    this.app = app;
    this.getSettings = getSettings;
    this.navHistoryGetter = navHistoryGetter;
    this.dragBar = null;
    this.countHandler = null;
    this.breadcrumbHandler = null;
    this.layoutHandler = null;
    this.renameHandler = null;
    this.statusBarOriginalParent = null;
    this.statusBarOriginalNextSibling = null;
  }
  apply() {
    this.remove();
    if (!this.getSettings().disableNoteTabs) return;
    const rootEl = this.app.workspace.rootSplit.containerEl;
    const tabsEl = rootEl.querySelector(".workspace-tabs");
    if (!tabsEl) return;
    this.dragBar = createDiv();
    this.dragBar.className = "minimalism-ui-drag-bar";
    const row1 = createDiv();
    row1.className = "minimalism-ui-drag-bar-row1";
    this.dragBar.appendChild(row1);
    const titleEl = createSpan();
    titleEl.className = "minimalism-ui-drag-bar-title";
    row1.appendChild(titleEl);
    const countEl = createSpan();
    countEl.className = "minimalism-ui-drag-bar-count";
    titleEl.appendChild(countEl);
    const breadcrumbEl = createDiv();
    breadcrumbEl.className = "minimalism-ui-drag-bar-breadcrumb";
    titleEl.appendChild(breadcrumbEl);
    tabsEl.insertBefore(this.dragBar, tabsEl.firstChild);
    const updateCount = () => {
      let count = 0;
      this.app.workspace.iterateRootLeaves(() => {
        count++;
      });
      countEl.textContent = String(count);
    };
    updateCount();
    this.countHandler = updateCount;
    this.app.workspace.on("active-leaf-change", updateCount);
    this.renameHandler = (file) => {
      if (file === this.app.workspace.getActiveFile()) updateBreadcrumb();
    };
    this.app.vault.on("rename", this.renameHandler);
    this.layoutHandler = () => {
      if (!this.dragBar || this.dragBar.isConnected) return;
      const rootEl2 = this.app.workspace.rootSplit.containerEl;
      const tabsEl2 = rootEl2.querySelector(".workspace-tabs");
      if (tabsEl2) tabsEl2.insertBefore(this.dragBar, tabsEl2.firstChild);
      updateCount();
    };
    this.app.workspace.on("layout-change", this.layoutHandler);
    const renderAll = (el, names) => {
      el.innerHTML = "";
      names.forEach((name, i) => {
        if (i > 0) {
          const sep = createSpan();
          sep.className = "minimalism-ui-breadcrumb-sep";
          sep.textContent = "/";
          el.appendChild(sep);
        }
        const item = createSpan();
        item.className = i === names.length - 1 ? "minimalism-ui-breadcrumb-item is-current" : "minimalism-ui-breadcrumb-item";
        item.textContent = name;
        el.appendChild(item);
      });
    };
    const renderCompact = (el, names, collapsedCount) => {
      el.innerHTML = "";
      const first = createSpan();
      first.className = "minimalism-ui-breadcrumb-item";
      first.textContent = names[0];
      el.appendChild(first);
      const sep1 = createSpan();
      sep1.className = "minimalism-ui-breadcrumb-sep";
      sep1.textContent = "/";
      el.appendChild(sep1);
      const collapse = createSpan();
      collapse.className = "minimalism-ui-breadcrumb-collapse";
      collapse.textContent = `\xB7\xB7\xB7${collapsedCount}\xB7\xB7\xB7`;
      el.appendChild(collapse);
      const sep2 = createSpan();
      sep2.className = "minimalism-ui-breadcrumb-sep";
      sep2.textContent = "/";
      el.appendChild(sep2);
      const last = createSpan();
      last.className = "minimalism-ui-breadcrumb-item is-current";
      last.textContent = names[names.length - 1];
      el.appendChild(last);
    };
    const showSingleFile = () => {
      breadcrumbEl.innerHTML = "";
      const activeFile = this.app.workspace.getActiveFile();
      if (!activeFile) return;
      const item = createSpan();
      item.className = "minimalism-ui-breadcrumb-item is-current";
      item.textContent = LeafNameUtils.stripPrefix(activeFile.basename, this.getSettings().filenamePrefixLength);
      breadcrumbEl.appendChild(item);
    };
    const updateBreadcrumb = () => {
      const prefixLen = this.getSettings().filenamePrefixLength;
      if (!this.getSettings().showBreadcrumb) {
        showSingleFile();
        return;
      }
      const paths = this.navHistoryGetter();
      if (paths.length <= 1) {
        showSingleFile();
        return;
      }
      const names = paths.map((p) => {
        const f = this.app.vault.getAbstractFileByPath(p);
        return f instanceof import_obsidian2.TFile ? LeafNameUtils.stripPrefix(f.basename, prefixLen) : LeafNameUtils.stripPrefix(p, prefixLen);
      });
      if (paths.length > COMPACT_THRESHOLD) {
        renderCompact(breadcrumbEl, names, names.length - 2);
        return;
      }
      renderAll(breadcrumbEl, names);
      requestAnimationFrame(() => {
        if (!breadcrumbEl.isConnected) return;
        if (breadcrumbEl.clientWidth === 0) return;
        if (breadcrumbEl.scrollWidth > breadcrumbEl.clientWidth && names.length > 2) {
          renderCompact(breadcrumbEl, names, names.length - 2);
        }
      });
    };
    updateBreadcrumb();
    this.breadcrumbHandler = updateBreadcrumb;
    this.app.workspace.on("active-leaf-change", updateBreadcrumb);
    const statusBar = activeDocument.querySelector(".status-bar");
    if (statusBar) {
      this.statusBarOriginalParent = statusBar.parentElement;
      this.statusBarOriginalNextSibling = statusBar.nextElementSibling;
      row1.appendChild(statusBar);
    }
  }
  remove() {
    if (this.countHandler) {
      this.app.workspace.off("active-leaf-change", this.countHandler);
      this.countHandler = null;
    }
    if (this.breadcrumbHandler) {
      this.app.workspace.off("active-leaf-change", this.breadcrumbHandler);
      this.breadcrumbHandler = null;
    }
    if (this.renameHandler) {
      this.app.vault.off("rename", this.renameHandler);
      this.renameHandler = null;
    }
    if (this.layoutHandler) {
      this.app.workspace.off("layout-change", this.layoutHandler);
      this.layoutHandler = null;
    }
    if (this.statusBarOriginalParent) {
      const statusBar = activeDocument.querySelector(".status-bar");
      if (statusBar) {
        if (this.statusBarOriginalNextSibling) {
          this.statusBarOriginalParent.insertBefore(statusBar, this.statusBarOriginalNextSibling);
        } else {
          this.statusBarOriginalParent.appendChild(statusBar);
        }
      }
      this.statusBarOriginalParent = null;
      this.statusBarOriginalNextSibling = null;
    }
    if (this.dragBar) {
      this.dragBar.remove();
      this.dragBar = null;
    }
  }
};

// src/SinglePageManager.ts
var SinglePageManager = class {
  constructor(app, getSettings, tabCache) {
    this.app = app;
    this.getSettings = getSettings;
    this.tabCache = tabCache;
    // ── Pin block ────────────────────────────────────────────────────────────
    this.pinBlockHandler = null;
    // ── Home page ────────────────────────────────────────────────────────────
    this.homePageHandler = null;
  }
  // ── Pin block ─────────────────────────────────────────────────────────────
  /** Set up right-click pin blocking. Safe to call before layout is ready. */
  apply() {
    this.removePinBlock();
    if (!this.getSettings().disablePinTab) return;
    this.pinBlockHandler = (e) => {
      if (e.target.closest(".workspace-tab-header.tappable")) {
        e.stopImmediatePropagation();
        e.preventDefault();
      }
    };
    activeDocument.addEventListener("contextmenu", this.pinBlockHandler, true);
  }
  removePinBlock() {
    if (this.pinBlockHandler) {
      activeDocument.removeEventListener("contextmenu", this.pinBlockHandler, true);
      this.pinBlockHandler = null;
    }
  }
  // ── Home page ─────────────────────────────────────────────────────────────
  /** Register the file-open listener. Must be called after layout is ready. */
  applyHomePage() {
    this.removeHomePage();
    if (!this.getSettings().homePage) return;
    this.homePageHandler = (file) => {
      if (!file) {
        const active = this.app.workspace.getMostRecentLeaf();
        if (active && this.tabCache.hasPendingIntercept(active)) return;
        void this.tabCache.openHomePage();
      }
    };
    this.app.workspace.on("file-open", this.homePageHandler);
  }
  async openHomePage() {
    return this.tabCache.openHomePage();
  }
  removeHomePage() {
    if (this.homePageHandler) {
      this.app.workspace.off("file-open", this.homePageHandler);
      this.homePageHandler = null;
    }
  }
  // ── Cleanup ───────────────────────────────────────────────────────────────
  remove() {
    this.removePinBlock();
    this.removeHomePage();
  }
};

// src/SidebarLayoutManager.ts
var import_obsidian3 = require("obsidian");
var SidebarLayoutManager = class {
  constructor(app, getSettings, tabCache) {
    this.app = app;
    this.getSettings = getSettings;
    this.tabCache = tabCache;
    // Guard against concurrent calls: each `apply()` awaits async ops, so a
    // second call arriving mid-flight would create duplicate leaves.
    this.isApplying = false;
    // Saved state for reversible injection — one record per injected element.
    this.injectedItems = [];
    this.hiddenShells = [];
    // Elements created (not moved) by apply() — removed entirely on cleanup.
    this.createdEls = [];
    // Workspace resize event ref — notifies the graph iframe renderer when sidebar width changes.
    this.graphResizeRef = null;
    this.injectedGraphLeaf = null;
    this.graphResizeObserver = null;
    // Monkey-patched testCSS ref — restored on remove().
    this.patchedRenderer = null;
    this.origTestCSS = null;
  }
  // ── Public ────────────────────────────────────────────────────────────────
  /** Undo all DOM injections and restore leaves to their original state. */
  remove() {
    var _a;
    if (this.injectedItems.length === 0 && this.hiddenShells.length === 0 && this.createdEls.length === 0) return;
    for (const { el, originalParent, originalNextSibling, addedClass } of this.injectedItems) {
      if (addedClass) el.classList.remove(addedClass);
      originalParent.insertBefore(el, originalNextSibling);
    }
    for (const shell of this.hiddenShells) {
      shell.classList.remove("minimalism-ui-is-hidden");
    }
    for (const el of this.createdEls) {
      el.remove();
    }
    if (this.graphResizeRef) {
      this.app.workspace.offref(this.graphResizeRef);
      this.graphResizeRef = null;
    }
    (_a = this.graphResizeObserver) == null ? void 0 : _a.disconnect();
    this.graphResizeObserver = null;
    this.injectedGraphLeaf = null;
    if (this.patchedRenderer && this.origTestCSS) {
      this.patchedRenderer.testCSS = this.origTestCSS;
      this.patchedRenderer = null;
      this.origTestCSS = null;
    }
    this.injectedItems = [];
    this.hiddenShells = [];
    this.createdEls = [];
  }
  async apply() {
    this.remove();
    if (!this.getSettings().macSidebar) return;
    if (this.isApplying) return;
    this.isApplying = true;
    try {
      const { workspace } = this.app;
      const leftSplit = workspace.leftSplit;
      const { showProperties, showLocalGraph } = this.getSettings();
      this.clearLeftSidebar();
      if (leftSplit == null ? void 0 : leftSplit.collapsed) leftSplit.expand();
      const outlineLeaf = workspace.getLeftLeaf(false);
      if (outlineLeaf) {
        await outlineLeaf.setViewState({ type: "outline", active: false });
      }
      let graphLeaf = null;
      if (showLocalGraph) {
        graphLeaf = workspace.getLeftLeaf(true);
        if (graphLeaf) {
          await graphLeaf.setViewState({ type: "localgraph", active: false });
        }
      }
      let propsLeaf = null;
      if (showProperties) {
        propsLeaf = workspace.getLeftLeaf(true);
        if (propsLeaf) {
          await propsLeaf.setViewState({ type: "file-properties", active: false });
        }
      }
      if (!showProperties && !showLocalGraph) return;
      await new Promise((resolve) => activeWindow.setTimeout(resolve, 100));
      const activeFile = workspace.getActiveFile();
      if (activeFile) {
        workspace.trigger("file-open", activeFile);
        await new Promise((resolve) => activeWindow.setTimeout(resolve, 50));
      }
      if (outlineLeaf && propsLeaf) {
        this.injectMetadataIntoOutline(outlineLeaf, propsLeaf);
      }
      if (outlineLeaf && graphLeaf) {
        this.injectLocalGraphIntoOutline(outlineLeaf, graphLeaf);
      }
    } finally {
      this.isApplying = false;
    }
  }
  // ── Private ───────────────────────────────────────────────────────────────
  /**
   * Moves `.metadata-content` (direct child of `.metadata-container`) from
   * the Properties leaf into the Outline leaf's `.workspace-leaf-content`.
   * The now-empty Properties workspace-tabs shell is hidden.
   */
  injectMetadataIntoOutline(outlineLeaf, propsLeaf) {
    const outlineEl = outlineLeaf.containerEl;
    const propsEl = propsLeaf.containerEl;
    const metadataContent = propsEl.querySelector(
      ".metadata-container > .metadata-content"
    );
    const outlineLeafContent = outlineEl.querySelector(
      '.workspace-leaf-content[data-type="outline"]'
    );
    if (!metadataContent || !outlineLeafContent) return;
    const originalParent = metadataContent.parentElement;
    const originalNextSibling = metadataContent.nextSibling;
    outlineLeafContent.appendChild(metadataContent);
    this.injectedItems.push({ el: metadataContent, originalParent, originalNextSibling });
    const propsWorkspaceTabs = propsEl.closest(".workspace-tabs");
    if (propsWorkspaceTabs) {
      propsWorkspaceTabs.classList.add("minimalism-ui-is-hidden");
      this.hiddenShells.push(propsWorkspaceTabs);
    }
  }
  /**
   * Moves the Local Graph's entire `.workspace-leaf-content` (the view's containerEl)
   * into the Outline leaf's `.workspace-leaf-content`, above the Properties panel.
   *
   * Why the whole containerEl and not just .view-content:
   *   Obsidian's graph view registers all mouse/wheel event listeners on
   *   `this.containerEl` (.workspace-leaf-content[data-type="localgraph"]).
   *   If only .view-content is moved, canvas events bubble up through the new
   *   DOM parent (outline's containerEl) and never reach the original, now-hidden
   *   localgraph containerEl — making the graph completely non-interactive.
   *   Moving the containerEl itself keeps the event listeners wired up.
   *
   * The class `minimalism-ui-injected-graph` is added for CSS targeting.
   */
  injectLocalGraphIntoOutline(outlineLeaf, graphLeaf) {
    var _a, _b, _c;
    const outlineEl = outlineLeaf.containerEl;
    const graphEl = graphLeaf.containerEl;
    const graphLeafContent = graphEl.querySelector(
      '.workspace-leaf-content[data-type="localgraph"]'
    );
    const outlineLeafContent = outlineEl.querySelector(
      '.workspace-leaf-content[data-type="outline"]'
    );
    if (!graphLeafContent || !outlineLeafContent) return;
    const originalParent = graphLeafContent.parentElement;
    const originalNextSibling = graphLeafContent.nextSibling;
    const addedClass = "minimalism-ui-injected-graph";
    graphLeafContent.classList.add(addedClass);
    const viewContent = graphLeafContent.querySelector(".view-content");
    const graphControls = graphLeafContent.querySelector(".graph-controls");
    if (graphControls && !graphControls.classList.contains("is-close")) {
      graphControls.classList.add("is-close");
    }
    const header = createDiv();
    header.className = "minimalism-ui-graph-header";
    const titleSpan = createSpan();
    titleSpan.textContent = "Local graph";
    header.appendChild(titleSpan);
    if (viewContent) {
      graphLeafContent.insertBefore(header, viewContent);
    } else {
      graphLeafContent.prepend(header);
    }
    this.createdEls.push(header);
    outlineLeafContent.appendChild(graphLeafContent);
    this.injectedItems.push({ el: graphLeafContent, originalParent, originalNextSibling, addedClass });
    const graphWorkspaceTabs = (_a = graphEl.closest(".workspace-tabs")) != null ? _a : graphEl;
    if (graphWorkspaceTabs) {
      graphWorkspaceTabs.classList.add("minimalism-ui-is-hidden");
      this.hiddenShells.push(graphWorkspaceTabs);
    }
    this.injectedGraphLeaf = graphLeaf;
    if (this.graphResizeRef) {
      this.app.workspace.offref(this.graphResizeRef);
      this.graphResizeRef = null;
    }
    (_b = this.graphResizeObserver) == null ? void 0 : _b.disconnect();
    const leftSplitEl = this.app.workspace.leftSplit;
    const observeTarget = (_c = leftSplitEl == null ? void 0 : leftSplitEl.containerEl) != null ? _c : activeDocument.querySelector(".workspace-split.mod-left-split");
    if (observeTarget) {
      this.graphResizeObserver = new ResizeObserver((entries) => {
        var _a2, _b2, _c2;
        const w = entries[0].contentRect.width;
        if (w > 0) {
          graphLeafContent.setCssProps({ "--minimalism-ui-graph-height": `${Math.round(w * 3 / 4)}px` });
        }
        (_c2 = (_b2 = (_a2 = this.injectedGraphLeaf) == null ? void 0 : _a2.view) == null ? void 0 : _b2.onResize) == null ? void 0 : _c2.call(_b2);
      });
      this.graphResizeObserver.observe(observeTarget);
    }
    activeWindow.setTimeout(() => {
      const w = graphLeafContent.getBoundingClientRect().width;
      if (w > 0) {
        graphLeafContent.setCssProps({ "--minimalism-ui-graph-height": `${Math.round(w * 3 / 4)}px` });
      }
      this.applyGraphColors();
    }, 200);
  }
  applyGraphColors() {
    var _a, _b;
    const renderer = (_b = (_a = this.injectedGraphLeaf) == null ? void 0 : _a.view) == null ? void 0 : _b.renderer;
    if (!(renderer == null ? void 0 : renderer.testCSS)) return;
    if (this.patchedRenderer && this.origTestCSS) {
      this.patchedRenderer.testCSS = this.origTestCSS;
    }
    const orig = renderer.testCSS.bind(renderer);
    this.patchedRenderer = renderer;
    this.origTestCSS = orig;
    renderer.testCSS = () => {
      activeDocument.body.classList.add("minimalism-ui-sidebar-graph-reading");
      orig();
      activeDocument.body.classList.remove("minimalism-ui-sidebar-graph-reading");
    };
    renderer.testCSS();
  }
  // ── Public helpers ────────────────────────────────────────────────────────
  /**
   * Clears every leaf from the left sidebar using three complementary strategies:
   *
   *   A. Walk leftSplit's internal workspace-item tree directly.
   *      Works regardless of DOM state (collapsed sidebar, mid-rebuild, etc.).
   *
   *   B. DOM traversal via containerEl.closest('.mod-left-split').
   *      Catches leaves whose workspace-item tree position wasn't found in A
   *      (e.g. floating / detached DOM fragments that still reference a split).
   *
   *   C. Full iterateAllLeaves sweep for the outline type.
   *      Guards against leaves that survived A and B because their containerEl
   *      was missing or not yet attached to the document.
   *
   * Results from all three are de-duplicated via a Set before detaching.
   *
   * NOTE: TabCacheManager patches leaf.detach() for sidebar leaves when disablePinTab
   * is enabled. We bypass this via tabCache.forceDetachLeaf().
   */
  clearLeftSidebar() {
    const { workspace } = this.app;
    const all = /* @__PURE__ */ new Set();
    const leftSplit = workspace.leftSplit;
    for (const leaf of this.collectLeavesFromItem(leftSplit)) {
      all.add(leaf);
    }
    workspace.iterateAllLeaves((leaf) => {
      const el = leaf.containerEl;
      if (el == null ? void 0 : el.closest(".workspace-split.mod-left-split")) {
        all.add(leaf);
      }
    });
    for (const leaf of all) {
      try {
        this.forceDetach(leaf);
      } catch (e) {
      }
    }
    const stragglers = [];
    workspace.iterateAllLeaves((leaf) => {
      const type = leaf.getViewState().type;
      if (type === "outline") stragglers.push(leaf);
    });
    for (const leaf of stragglers) {
      try {
        this.forceDetach(leaf);
      } catch (e) {
      }
    }
  }
  forceDetach(leaf) {
    this.tabCache.forceDetachLeaf(leaf);
  }
  /**
   * Recursively collects all WorkspaceLeaf instances from a workspace item
   * (WorkspaceSplit / WorkspaceSidedock / WorkspaceTabs / WorkspaceLeaf).
   */
  collectLeavesFromItem(item) {
    if (!item || typeof item !== "object") return [];
    if (item instanceof import_obsidian3.WorkspaceLeaf) return [item];
    const children = item.children;
    if (!Array.isArray(children)) return [];
    return children.flatMap((child) => this.collectLeavesFromItem(child));
  }
};

// src/MermaidZoomManager.ts
var MermaidZoomManager = class {
  constructor(app, getSettings) {
    this.mutationObs = null;
    this.app = app;
    this.getSettings = getSettings;
    this.clickHandler = this.onClick.bind(this);
  }
  apply() {
    activeDocument.addEventListener("click", this.clickHandler, true);
    this.mutationObs = new MutationObserver((mutations) => {
      for (const m of mutations) {
        for (const node of Array.from(m.addedNodes)) {
          if (!(node instanceof Element)) continue;
          if (node.classList.contains("mermaid")) {
            this.scheduleMarkOverflow(node);
          } else {
            node.querySelectorAll(".mermaid").forEach((el) => this.scheduleMarkOverflow(el));
          }
        }
      }
    });
    this.mutationObs.observe(activeDocument.body, { childList: true, subtree: true });
    activeDocument.querySelectorAll(".mermaid").forEach((el) => this.scheduleMarkOverflow(el));
  }
  remove() {
    var _a;
    activeDocument.removeEventListener("click", this.clickHandler, true);
    (_a = this.mutationObs) == null ? void 0 : _a.disconnect();
    this.mutationObs = null;
    activeDocument.querySelectorAll(".mermaid").forEach((el) => {
      el.classList.remove("mermaid-fit-view", "mermaid-overflows");
    });
  }
  // ─── Private ──────────────────────────────────────────────────────────────
  onClick(e) {
    if (!this.getSettings().noteStyle) return;
    const mermaidEl = e.target.closest(".mermaid");
    if (!mermaidEl || !mermaidEl.classList.contains("mermaid-overflows")) return;
    if (mermaidEl.classList.contains("mermaid-fit-view")) {
      mermaidEl.classList.remove("mermaid-fit-view");
    } else {
      mermaidEl.classList.add("mermaid-fit-view");
    }
  }
  /** 等一帧再检查，确保 SVG 已完成渲染并写入 width 属性 */
  scheduleMarkOverflow(el) {
    requestAnimationFrame(() => this.markOverflow(el));
  }
  markOverflow(el) {
    var _a;
    const svg = el.querySelector("svg");
    if (!svg) return;
    const naturalWidth = parseFloat((_a = svg.getAttribute("width")) != null ? _a : "0");
    const containerWidth = el.clientWidth;
    const overflows = naturalWidth > containerWidth + 2;
    el.classList.toggle("mermaid-overflows", overflows);
    if (overflows) {
      el.classList.add("mermaid-fit-view");
    } else {
      el.classList.remove("mermaid-fit-view");
    }
  }
};

// src/SettingTab.ts
var import_obsidian4 = require("obsidian");

// src/i18n.ts
var translations = {
  zh: {
    language: "\u8BED\u8A00",
    languageAuto: "\u8DDF\u968F\u7CFB\u7EDF",
    languageZh: "\u4E2D\u6587",
    languageEn: "English",
    headingAppearance: "\u5916\u89C2\u8BBE\u7F6E",
    headingInteraction: "\u5355\u9875\u6A21\u5F0F\u8BBE\u7F6E",
    macSidebar: "\u6781\u7B80\u4FA7\u8FB9\u680F",
    macSidebarDesc: "\u4E3A\u5DE6\u4FA7\u8FB9\u680F\u5E94\u7528\u78E8\u7802\u73BB\u7483\u80CC\u666F\u4E0E\u5706\u89D2\u9AD8\u4EAE\uFF0C\u6253\u9020 macOS \u539F\u751F\u98CE\u683C\u3002",
    showProperties: "\u663E\u793A\u5C5E\u6027\u9762\u677F",
    showPropertiesDesc: "\u5728\u4FA7\u8FB9\u680F\u5DE6\u4E0B\u89D2\u663E\u793A\u5F53\u524D\u7B14\u8BB0\u7684\u5C5E\u6027\uFF08Properties\uFF09\u3002",
    showLocalGraph: "\u663E\u793A\u672C\u5730\u5173\u7CFB\u56FE",
    showLocalGraphDesc: "\u5728\u4FA7\u8FB9\u680F\u663E\u793A\u5F53\u524D\u7B14\u8BB0\u7684\u672C\u5730\u5173\u7CFB\u56FE\uFF08Local Graph\uFF09\uFF0C\u4F4D\u4E8E\u5C5E\u6027\u9762\u677F\u4E0A\u65B9\u3002",
    hideTabBar: "\u6781\u7B80\u4FE1\u606F\u680F",
    hideTabBarDesc: "\u9690\u85CF\u5DE6\u4FA7\u5C5E\u6027\u680F\u7684\u64CD\u4F5C\u6309\u94AE\uFF0C\u4EE5\u53CA\u5927\u7EB2\u3001\u53CD\u5411\u94FE\u63A5\u9762\u677F\u4E2D\u7684\u641C\u7D22\u6846",
    noteStyle: "\u7B14\u8BB0\u6837\u5F0F\u4F18\u5316",
    noteStyleDesc: "\u5BF9\u7F16\u8F91\u5668\u4E0E\u9605\u8BFB\u89C6\u56FE\u5E94\u7528\u4EE5\u4E0B\u5B9A\u5236\u6837\u5F0F\uFF1A",
    noteStyleItem1: "\u5B57\u4F53\uFF1A\u6B63\u6587\u6570\u5B57\u4F7F\u7528 JetBrains Mono \u7B49\u5BBD\u5B57\u4F53\u6DF7\u6392",
    noteStyleItem2: "\u5F15\u7528\u5757\u3001\u8868\u683C\u3001\u4EE3\u7801\u5757\uFF1AForest \u98CE\u683C\u6837\u5F0F\u5B9A\u5236",
    noteStyleItem3: "Mermaid \u56FE\u8868\uFF1A\u8D85\u5BBD\u56FE\u8868\u9ED8\u8BA4\u7F29\u653E\u663E\u793A\u5168\u56FE\uFF0C\u70B9\u51FB\u540E\u67E5\u770B\u539F\u59CB\u5C3A\u5BF8",
    homePage: "\u7B14\u8BB0\u9996\u9875",
    homePageDesc: "\u8BBE\u7F6E\u4E00\u4E2A\u7B14\u8BB0\u4F5C\u4E3A\u9996\u9875\u3002Obsidian \u542F\u52A8\u65F6\u81EA\u52A8\u6253\u5F00\uFF0C\u5173\u95ED\u6240\u6709\u6807\u7B7E\u540E\u81EA\u52A8\u8FD4\u56DE\u3002",
    homePagePlaceholder: "\u8F93\u5165\u7B14\u8BB0\u8DEF\u5F84\uFF0C\u4F8B\u5982\uFF1Asrc/Home.md",
    singlePage: "\u5F00\u542F\u5355\u9875\u6A21\u5F0F",
    singlePageDesc1: "1. \u9690\u85CF\u9876\u90E8\u6807\u7B7E\u680F\uFF0C\u6BCF\u6B21\u53EA\u5C55\u793A\u4E00\u7BC7\u7B14\u8BB0\u3002",
    singlePageDesc2: "2. \u542F\u7528\u9875\u9762\u7F13\u5B58\uFF0C\u5728\u5185\u5B58\u4E2D\u4FDD\u7559\u6700\u8FD1\u8BBF\u95EE\u7684 10 \u4E2A\u9875\u9762",
    singlePageDesc3: "3. \u7981\u7528 pin \u6807\u7B7E\u529F\u80FD\uFF0C\u907F\u514D\u591A\u4F59\u7684\u6807\u7B7E\u88AB\u56FA\u5B9A\u5728\u9876\u90E8\u3002",
    navAnimation: "\u9875\u9762\u52A0\u8F7D\u52A8\u753B (beta)",
    navAnimationDesc: "\u524D\u8FDB\u6216\u540E\u9000\u65F6\uFF0C\u4E3A\u76EE\u6807\u9875\u9762\u64AD\u653E\u6ED1\u5165\u52A8\u753B",
    filenamePrefixLength: "\u9690\u85CF\u6587\u4EF6\u540D\u524D\u7F00",
    filenamePrefixLengthDesc: '\u5728\u6587\u4EF6\u6D4F\u89C8\u5668\u548C\u6807\u7B7E\u9875\u4E2D\u9690\u85CF\u6587\u4EF6\u540D\u5F00\u5934\u7684 N \u4E2A\u5B57\u7B26\uFF080 = \u4E0D\u9690\u85CF\uFF0C\u6700\u591A 20\uFF09\u3002\u9002\u7528\u4E8E\u65F6\u95F4\u6233\u524D\u7F00\u7B14\u8BB0\uFF0C\u5982\u9690\u85CF "202604111230-" \u524D 13 \u4E2A\u5B57\u7B26\u3002',
    showBreadcrumb: "\u663E\u793A\u9762\u5305\u5C51\u5BFC\u822A",
    showBreadcrumbDesc: "\u5728\u9876\u90E8\u62D6\u62FD\u680F\u663E\u793A\u5F53\u524D\u9875\u9762\u7684\u8BBF\u95EE\u8DEF\u5F84\uFF08\u9762\u5305\u5C51\uFF09\uFF0C\u65B9\u4FBF\u8FFD\u8E2A\u5BFC\u822A\u5386\u53F2\u3002"
  },
  en: {
    language: "Language",
    languageAuto: "Follow system",
    languageZh: "\u4E2D\u6587",
    languageEn: "English",
    headingAppearance: "Appearance",
    headingInteraction: "Interaction",
    macSidebar: "Minimal Sidebar",
    macSidebarDesc: "Apply a frosted-glass background and rounded highlights to the left sidebar for a macOS-native look.",
    showProperties: "Show Properties",
    showPropertiesDesc: "Display the current note's properties at the bottom of the sidebar.",
    showLocalGraph: "Show Local Graph",
    showLocalGraphDesc: "Display the local graph for the current note in the sidebar, above the properties panel.",
    hideTabBar: "Minimal Info Bar",
    hideTabBarDesc: "Hide action buttons in the properties panel and search bars in the Outline / Backlinks panels.",
    noteStyle: "Note Style",
    noteStyleDesc: "Apply the following custom styles to the editor and reading view:",
    noteStyleItem1: "Typography: JetBrains Mono for inline digits in body text",
    noteStyleItem2: "Blockquotes, tables, code blocks: Forest-style design",
    noteStyleItem3: "Mermaid diagrams: wide diagrams scale to fit by default; click to view at full size",
    homePage: "Home Note",
    homePageDesc: "A note that opens automatically on startup and whenever all tabs are closed.",
    homePagePlaceholder: "Note path, e.g. src/Home.md",
    singlePage: "Single-Page Mode",
    singlePageDesc1: "1. Hide the tab bar \u2014 show one note at a time.",
    singlePageDesc2: "2. Keep the 10 most recently visited notes cached in memory.",
    singlePageDesc3: "3. Disable tab pinning to prevent tabs from being pinned.",
    navAnimation: "Page Transition Animation (beta)",
    navAnimationDesc: "Play a slide-in animation when navigating back or forward.",
    filenamePrefixLength: "Hide Filename Prefix",
    filenamePrefixLengthDesc: 'Hide the first N characters of filenames in the file explorer and tabs (0 = off, max 20). Useful for timestamp-prefixed notes, e.g. hide the first 13 chars of "202604111230-".',
    showBreadcrumb: "Show Breadcrumb",
    showBreadcrumbDesc: "Show a breadcrumb trail in the drag bar to track your navigation history."
  }
};
var langOverride = null;
function setLang(lang) {
  langOverride = lang === "auto" ? null : lang;
}
function detectLang() {
  var _a, _b;
  if (langOverride) return langOverride;
  const lang = (_b = (_a = activeDocument.documentElement.lang) == null ? void 0 : _a.slice(0, 2)) != null ? _b : "en";
  return lang in translations ? lang : "en";
}
function t(key) {
  return translations[detectLang()][key];
}

// src/SettingTab.ts
var FileSuggest = class extends import_obsidian4.AbstractInputSuggest {
  constructor() {
    super(...arguments);
    this.onPickCb = null;
  }
  onPick(cb) {
    this.onPickCb = cb;
    return this;
  }
  getSuggestions(query) {
    return this.app.vault.getMarkdownFiles().filter((f) => f.path.toLowerCase().includes(query.toLowerCase())).slice(0, 20);
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    var _a;
    this.setValue(file.path);
    (_a = this.onPickCb) == null ? void 0 : _a.call(this, file.path);
    this.close();
  }
};
var MinimalismUISettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName(t("language")).addDropdown((drop) => drop.addOption("auto", t("languageAuto")).addOption("zh", t("languageZh")).addOption("en", t("languageEn")).setValue(this.plugin.settings.language).onChange(async (v) => {
      this.plugin.settings.language = v;
      setLang(v);
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian4.Setting(containerEl).setName(t("headingAppearance")).setHeading();
    new import_obsidian4.Setting(containerEl).setName(t("macSidebar")).setDesc(t("macSidebarDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.macSidebar).onChange(async (v) => {
      this.plugin.settings.macSidebar = v;
      await this.plugin.saveSettings();
      this.plugin.applyBodyClasses();
      showPropertiesSetting.settingEl.toggle(v);
      showLocalGraphSetting.settingEl.toggle(v);
      await this.plugin.applyMacSidebarLayout();
    }));
    const showPropertiesSetting = new import_obsidian4.Setting(containerEl).setName(t("showProperties")).setDesc(t("showPropertiesDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showProperties).onChange(async (v) => {
      this.plugin.settings.showProperties = v;
      await this.plugin.saveSettings();
      await this.plugin.applyMacSidebarLayout();
    }));
    showPropertiesSetting.settingEl.addClass("minimalism-ui-sub-setting");
    showPropertiesSetting.settingEl.toggle(this.plugin.settings.macSidebar);
    const showLocalGraphSetting = new import_obsidian4.Setting(containerEl).setName(t("showLocalGraph")).setDesc(t("showLocalGraphDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showLocalGraph).onChange(async (v) => {
      this.plugin.settings.showLocalGraph = v;
      await this.plugin.saveSettings();
      await this.plugin.applyMacSidebarLayout();
    }));
    showLocalGraphSetting.settingEl.addClass("minimalism-ui-sub-setting");
    showLocalGraphSetting.settingEl.toggle(this.plugin.settings.macSidebar);
    new import_obsidian4.Setting(containerEl).setName(t("hideTabBar")).setDesc(t("hideTabBarDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.hideTabBar).onChange(async (v) => {
      this.plugin.settings.hideTabBar = v;
      this.plugin.settings.simplifyPanel = v;
      await this.plugin.saveSettings();
    }));
    const noteStyleSetting = new import_obsidian4.Setting(containerEl).setName(t("noteStyle")).addToggle((toggle) => toggle.setValue(this.plugin.settings.noteStyle).onChange(async (v) => {
      this.plugin.settings.noteStyle = v;
      await this.plugin.saveSettings();
    }));
    noteStyleSetting.descEl.createSpan({ text: t("noteStyleDesc") });
    const noteStyleList = noteStyleSetting.descEl.createEl("ul");
    noteStyleList.createEl("li", { text: t("noteStyleItem1") });
    noteStyleList.createEl("li", { text: t("noteStyleItem2") });
    noteStyleList.createEl("li", { text: t("noteStyleItem3") });
    new import_obsidian4.Setting(containerEl).setName(t("headingInteraction")).setHeading();
    const singlePageSetting = new import_obsidian4.Setting(containerEl).setName(t("singlePage"));
    singlePageSetting.settingEl.addClass("minimalism-ui-single-page-setting");
    singlePageSetting.addToggle((toggle) => toggle.setValue(this.plugin.settings.disableNoteTabs).onChange(async (v) => {
      this.plugin.settings.disableNoteTabs = v;
      this.plugin.settings.disablePinTab = v;
      this.plugin.settings.enableLeafCache = v;
      await this.plugin.saveSettings();
    }));
    singlePageSetting.descEl.createSpan({ text: t("singlePageDesc1") });
    singlePageSetting.descEl.createEl("br");
    singlePageSetting.descEl.createSpan({ text: t("singlePageDesc2") });
    singlePageSetting.descEl.createEl("br");
    singlePageSetting.descEl.createSpan({ text: t("singlePageDesc3") });
    singlePageSetting.descEl.createEl("br");
    new import_obsidian4.Setting(containerEl).setName(t("homePage")).setDesc(t("homePageDesc")).addText((text) => {
      text.setPlaceholder(t("homePagePlaceholder")).setValue(this.plugin.settings.homePage);
      new FileSuggest(this.app, text.inputEl).onPick((path) => {
        this.plugin.settings.homePage = path;
        void this.plugin.saveSettings();
      });
      text.inputEl.addEventListener("change", () => {
        this.plugin.settings.homePage = text.inputEl.value.trim();
        void this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("navAnimation")).setDesc(t("navAnimationDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.enableNavAnimation).onChange(async (v) => {
      this.plugin.settings.enableNavAnimation = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian4.Setting(containerEl).setName(t("filenamePrefixLength")).setDesc(t("filenamePrefixLengthDesc")).addText((text) => {
      text.inputEl.type = "number";
      text.inputEl.min = "0";
      text.inputEl.max = "20";
      text.inputEl.addClass("minimalism-ui-prefix-input");
      text.setValue(String(this.plugin.settings.filenamePrefixLength));
      text.inputEl.addEventListener("change", async () => {
        const raw = parseInt(text.inputEl.value, 10);
        const clamped = isNaN(raw) ? 0 : Math.min(20, Math.max(0, raw));
        text.setValue(String(clamped));
        this.plugin.settings.filenamePrefixLength = clamped;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName(t("showBreadcrumb")).setDesc(t("showBreadcrumbDesc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.showBreadcrumb).onChange(async (v) => {
      this.plugin.settings.showBreadcrumb = v;
      await this.plugin.saveSettings();
    }));
  }
};

// main.ts
var MinimalismUIPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.loadedFonts = [];
  }
  async onload() {
    await this.loadSettings();
    setLang(this.settings.language);
    this.tabCache = new TabCacheManager(
      this.app,
      () => this.settings
    );
    this.dragBar = new DragBarManager(
      this.app,
      () => this.settings,
      () => this.tabCache.getNavHistory()
    );
    this.sidebarLayout = new SidebarLayoutManager(this.app, () => this.settings, this.tabCache);
    this.singlePage = new SinglePageManager(
      this.app,
      () => this.settings,
      this.tabCache
    );
    this.mermaidZoom = new MermaidZoomManager(this.app, () => this.settings);
    await this.loadJetBrainsMono();
    this.applyBodyClasses();
    this.singlePage.apply();
    this.tabCache.apply();
    this.mermaidZoom.apply();
    this.app.workspace.onLayoutReady(() => {
      this.dragBar.apply();
      this.singlePage.applyHomePage();
      void this.singlePage.openHomePage();
      void this.sidebarLayout.apply();
    });
    this.addSettingTab(new MinimalismUISettingTab(this.app, this));
  }
  onunload() {
    setLang("auto");
    activeDocument.body.classList.remove(
      "minimalism-ui-mac-sidebar",
      "minimalism-ui-hide-tab-bar",
      "minimalism-ui-disable-pin",
      "minimalism-ui-simplify-panel",
      "minimalism-ui-disable-note-tabs",
      "minimalism-ui-note-style"
    );
    for (const font of this.loadedFonts) activeDocument.fonts.delete(font);
    this.loadedFonts = [];
    this.singlePage.remove();
    this.tabCache.remove();
    this.dragBar.remove();
    this.sidebarLayout.remove();
    this.mermaidZoom.remove();
  }
  // ─── Sidebar Layout ───────────────────────────────────────────────────────
  async applyMacSidebarLayout() {
    if (this.settings.macSidebar) {
      await this.sidebarLayout.apply();
    } else {
      this.sidebarLayout.remove();
    }
  }
  // ─── Body Classes ─────────────────────────────────────────────────────────
  applyBodyClasses() {
    const cls = activeDocument.body.classList;
    cls.toggle("minimalism-ui-mac-sidebar", this.settings.macSidebar);
    cls.toggle("minimalism-ui-hide-tab-bar", this.settings.hideTabBar);
    cls.toggle("minimalism-ui-disable-pin", this.settings.disablePinTab);
    cls.toggle("minimalism-ui-simplify-panel", this.settings.simplifyPanel);
    cls.toggle("minimalism-ui-disable-note-tabs", this.settings.disableNoteTabs);
    cls.toggle("minimalism-ui-note-style", this.settings.noteStyle);
  }
  // ─── Settings ─────────────────────────────────────────────────────────────
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyBodyClasses();
    this.singlePage.apply();
    this.tabCache.apply();
    this.dragBar.apply();
    this.singlePage.applyHomePage();
  }
  // ─── Fonts ────────────────────────────────────────────────────────────────
  fontPath(filename) {
    const adapter = this.app.vault.adapter;
    return adapter.getResourcePath(`${this.manifest.dir}/fonts/${filename}`);
  }
  async loadFontFace(family, descriptors) {
    const { file, ...desc } = descriptors;
    const face = new FontFace(family, `url('${this.fontPath(file)}')`, desc);
    try {
      await face.load();
      activeDocument.fonts.add(face);
      this.loadedFonts.push(face);
    } catch (e) {
    }
  }
  async loadJetBrainsMono() {
    const digitsRange = "U+002D, U+002E, U+0030-0039";
    await Promise.all([
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Regular.ttf", style: "normal", weight: "400" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Italic.ttf", style: "italic", weight: "400" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Medium.ttf", style: "normal", weight: "500" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-MediumItalic.ttf", style: "italic", weight: "500" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Bold.ttf", style: "normal", weight: "700" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-BoldItalic.ttf", style: "italic", weight: "700" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-ExtraBold.ttf", style: "normal", weight: "900" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-ExtraBoldItalic.ttf", style: "italic", weight: "900" }),
      // 数字专用字族：只覆盖数字 unicode 范围，用于正文混排
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-Regular.ttf", style: "normal", weight: "400", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-Italic.ttf", style: "italic", weight: "400", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-Medium.ttf", style: "normal", weight: "500", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-MediumItalic.ttf", style: "italic", weight: "500", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-Bold.ttf", style: "normal", weight: "700", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-BoldItalic.ttf", style: "italic", weight: "700", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-ExtraBold.ttf", style: "normal", weight: "900", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-ExtraBoldItalic.ttf", style: "italic", weight: "900", unicodeRange: digitsRange })
    ]);
  }
};
