/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin.
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MinimalismUIPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  macSidebar: false,
  hideTabBar: false,
  disablePinTab: true,
  simplifyPanel: false,
  disableNoteTabs: false,
  enableLeafCache: false,
  enableNavAnimation: false,
  noteStyle: false,
  homePage: ""
};

// src/TabCacheManager.ts
var TabCacheManager = class {
  // isOpeningHomePage 由 plugin 提供，避免首页打开时触发 getLeaf 拦截
  constructor(app, getSettings, isOpeningHomePage) {
    this.app = app;
    this.getSettings = getSettings;
    this.isOpeningHomePage = isOpeningHomePage;
    this.leafQueue = [];
    this.isReusingLeaf = false;
    this.isEvicting = false;
    this.originalGetLeaf = null;
    this.navHistory = [];
    this.navFuture = [];
    this.navJumpTarget = null;
    this.tabLimitHandler = null;
    this.navTrackHandler = null;
    this.navAnimateHandler = null;
    this.pendingAnimationCls = null;
    this.navTimer = null;
    this.resizeObserverErrHandler = null;
    this.historyPatches = /* @__PURE__ */ new Map();
    this.origGoBack = null;
    this.origGoForward = null;
    // 由 getLeaf patch 新建、尚未调用 openFile 的空 leaf
    this.pendingInterceptLeaves = /* @__PURE__ */ new Set();
  }
  apply() {
    this.remove();
    this.leafQueue = [];
    if (!this.getSettings().disableNoteTabs)
      return;
    const ws = this.app.workspace;
    this.originalGetLeaf = ws.getLeaf.bind(ws);
    ws.getLeaf = (newLeaf) => {
      const shouldIntercept = newLeaf === false || newLeaf === void 0 || newLeaf === true || newLeaf === "tab";
      if (shouldIntercept && !this.isReusingLeaf && !this.isOpeningHomePage()) {
        const leaf = this.originalGetLeaf("tab");
        this.interceptLeafOpenFile(leaf);
        return leaf;
      }
      return this.originalGetLeaf(newLeaf);
    };
    this.resizeObserverErrHandler = (e) => {
      if (e.message === "ResizeObserver loop completed with undelivered notifications.") {
        e.stopImmediatePropagation();
        e.preventDefault();
      }
    };
    window.addEventListener("error", this.resizeObserverErrHandler, true);
    this.tabLimitHandler = () => {
      if (this.isEvicting)
        return;
      const active = this.app.workspace.getMostRecentLeaf();
      if (!active)
        return;
      this.leafQueue = this.leafQueue.filter((l) => l !== active);
      this.leafQueue.push(active);
      const rootLeaves = [];
      this.app.workspace.iterateRootLeaves((l) => rootLeaves.push(l));
      this.leafQueue = this.leafQueue.filter((l) => rootLeaves.includes(l));
      const max = this.getSettings().enableLeafCache ? 10 : Infinity;
      if (this.leafQueue.length > max) {
        this.isEvicting = true;
        try {
          while (this.leafQueue.length > max) {
            const oldest = this.leafQueue.shift();
            oldest.detach();
          }
        } finally {
          this.isEvicting = false;
        }
      }
    };
    this.app.workspace.on("active-leaf-change", this.tabLimitHandler);
    this.navTrackHandler = (leaf) => {
      if (!leaf)
        return;
      if (leaf === this.navJumpTarget) {
        this.navJumpTarget = null;
        return;
      }
      let isRootLeaf = false;
      this.app.workspace.iterateRootLeaves((l) => {
        if (l === leaf)
          isRootLeaf = true;
      });
      if (!isRootLeaf)
        return;
      const last = this.navHistory[this.navHistory.length - 1];
      if (last === leaf)
        return;
      this.navHistory.push(leaf);
      this.navFuture = [];
    };
    this.app.workspace.on("active-leaf-change", this.navTrackHandler);
    this.navAnimateHandler = (leaf) => {
      if (!this.pendingAnimationCls || !leaf)
        return;
      const cls = this.pendingAnimationCls;
      this.pendingAnimationCls = null;
      if (!this.getSettings().enableNavAnimation)
        return;
      requestAnimationFrame(() => {
        var _a;
        const el = (_a = leaf.view) == null ? void 0 : _a.contentEl;
        if (!el)
          return;
        el.classList.remove("minimalism-ui-slide-from-left", "minimalism-ui-slide-from-right");
        requestAnimationFrame(() => {
          el.classList.add(cls);
          el.addEventListener("animationend", () => el.classList.remove(cls), { once: true });
        });
      });
    };
    this.app.workspace.on("active-leaf-change", this.navAnimateHandler);
    this.app.workspace.iterateRootLeaves((leaf) => this.patchLeafHistory(leaf));
    const appCmds = this.app.commands.commands;
    const backCmd = appCmds["app:go-back"];
    const fwdCmd = appCmds["app:go-forward"];
    if (backCmd) {
      this.origGoBack = { callback: backCmd.callback, checkCallback: backCmd.checkCallback };
      delete backCmd.callback;
      backCmd.checkCallback = (checking) => {
        if (checking)
          return this.navHistory.length >= 2;
        this.navigateBack();
        return true;
      };
    }
    if (fwdCmd) {
      this.origGoForward = { callback: fwdCmd.callback, checkCallback: fwdCmd.checkCallback };
      delete fwdCmd.callback;
      fwdCmd.checkCallback = (checking) => {
        if (checking)
          return this.navFuture.length > 0;
        this.navigateForward();
        return true;
      };
    }
  }
  remove() {
    if (this.originalGetLeaf) {
      this.app.workspace.getLeaf = this.originalGetLeaf;
      this.originalGetLeaf = null;
    }
    if (this.tabLimitHandler) {
      this.app.workspace.off("active-leaf-change", this.tabLimitHandler);
      this.tabLimitHandler = null;
    }
    if (this.navTrackHandler) {
      this.app.workspace.off("active-leaf-change", this.navTrackHandler);
      this.navTrackHandler = null;
    }
    if (this.navAnimateHandler) {
      this.app.workspace.off("active-leaf-change", this.navAnimateHandler);
      this.navAnimateHandler = null;
    }
    this.pendingAnimationCls = null;
    if (this.navTimer !== null) {
      clearTimeout(this.navTimer);
      this.navTimer = null;
    }
    if (this.resizeObserverErrHandler) {
      window.removeEventListener("error", this.resizeObserverErrHandler, true);
      this.resizeObserverErrHandler = null;
    }
    this.unpatchAllLeafHistories();
    const appCmds = this.app.commands.commands;
    if (this.origGoBack) {
      const cmd = appCmds["app:go-back"];
      if (cmd) {
        delete cmd.checkCallback;
        if (this.origGoBack.callback)
          cmd.callback = this.origGoBack.callback;
        if (this.origGoBack.checkCallback)
          cmd.checkCallback = this.origGoBack.checkCallback;
      }
      this.origGoBack = null;
    }
    if (this.origGoForward) {
      const cmd = appCmds["app:go-forward"];
      if (cmd) {
        delete cmd.checkCallback;
        if (this.origGoForward.callback)
          cmd.callback = this.origGoForward.callback;
        if (this.origGoForward.checkCallback)
          cmd.checkCallback = this.origGoForward.checkCallback;
      }
      this.origGoForward = null;
    }
    this.leafQueue = [];
    this.navHistory = [];
    this.navFuture = [];
    this.navJumpTarget = null;
    this.pendingInterceptLeaves.clear();
  }
  // 检查指定 leaf 是否正处于等待 openFile 的 pending 状态
  // 供外部（homePageHandler）判断：若为 pending 则不应触发首页跳转
  hasPendingIntercept(leaf) {
    return this.pendingInterceptLeaves.has(leaf);
  }
  // 对新建的空 leaf 注入一次性 openFile 拦截器：
  // 在文件实际加载前检查缓存，若已有相同文件的 leaf 则直接复用，避免闪烁
  interceptLeafOpenFile(leaf) {
    this.pendingInterceptLeaves.add(leaf);
    const origOpenFile = leaf.openFile.bind(leaf);
    leaf.openFile = async (file, state) => {
      leaf.openFile = origOpenFile;
      this.pendingInterceptLeaves.delete(leaf);
      if (!this.isReusingLeaf) {
        let existingLeaf = null;
        this.app.workspace.iterateRootLeaves((l) => {
          var _a, _b;
          if (existingLeaf || l === leaf)
            return;
          if (((_b = (_a = l.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) === file.path) {
            existingLeaf = l;
          }
        });
        if (existingLeaf) {
          this.isReusingLeaf = true;
          try {
            this.leafQueue = this.leafQueue.filter((l) => l !== existingLeaf);
            this.leafQueue.push(existingLeaf);
            this.app.workspace.setActiveLeaf(existingLeaf, { focus: true });
            leaf.detach();
          } finally {
            this.isReusingLeaf = false;
          }
          return;
        }
      }
      this.patchLeafHistory(leaf);
      return await origOpenFile(file, state);
    };
  }
  navigateBack() {
    if (this.navTimer !== null) {
      clearTimeout(this.navTimer);
      this.navTimer = null;
    }
    const snapHistory = [...this.navHistory];
    const snapFuture = [...this.navFuture];
    while (this.navHistory.length >= 2) {
      const current = this.navHistory.pop();
      this.navFuture.unshift(current);
      const prev = this.navHistory[this.navHistory.length - 1];
      if (prev.parent) {
        this.navJumpTarget = prev;
        this.pendingAnimationCls = "minimalism-ui-slide-from-left";
        this.navTimer = setTimeout(() => {
          this.navTimer = null;
          this.app.workspace.setActiveLeaf(prev, { focus: true });
        }, 0);
        return;
      }
    }
    this.navHistory = snapHistory;
    this.navFuture = snapFuture;
  }
  navigateForward() {
    if (this.navTimer !== null) {
      clearTimeout(this.navTimer);
      this.navTimer = null;
    }
    const snapHistory = [...this.navHistory];
    const snapFuture = [...this.navFuture];
    while (this.navFuture.length > 0) {
      const next = this.navFuture.shift();
      if (next.parent) {
        this.navHistory.push(next);
        this.navJumpTarget = next;
        this.pendingAnimationCls = "minimalism-ui-slide-from-right";
        this.navTimer = setTimeout(() => {
          this.navTimer = null;
          this.app.workspace.setActiveLeaf(next, { focus: true });
        }, 0);
        return;
      }
    }
    this.navHistory = snapHistory;
    this.navFuture = snapFuture;
  }
  patchLeafHistory(leaf) {
    var _a, _b;
    const history = leaf.history;
    if (!history || this.historyPatches.has(leaf))
      return;
    const origBack = history.back.bind(history);
    const origForward = history.forward.bind(history);
    const origCanGoBack = (_a = history.canGoBack) == null ? void 0 : _a.bind(history);
    const origCanGoForward = (_b = history.canGoForward) == null ? void 0 : _b.bind(history);
    history.back = () => this.navigateBack();
    history.forward = () => this.navigateForward();
    history.canGoBack = () => this.navHistory.length >= 2;
    history.canGoForward = () => this.navFuture.length > 0;
    this.historyPatches.set(leaf, { back: origBack, forward: origForward, canGoBack: origCanGoBack, canGoForward: origCanGoForward });
  }
  unpatchAllLeafHistories() {
    for (const [leaf, orig] of this.historyPatches) {
      const history = leaf.history;
      if (history) {
        history.back = orig.back;
        history.forward = orig.forward;
        if (orig.canGoBack !== void 0)
          history.canGoBack = orig.canGoBack;
        if (orig.canGoForward !== void 0)
          history.canGoForward = orig.canGoForward;
      }
    }
    this.historyPatches.clear();
  }
};

// src/DragBarManager.ts
var DragBarManager = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
    this.dragBar = null;
    this.titleHandler = null;
    this.layoutHandler = null;
    this.renameHandler = null;
    this.statusBarOriginalParent = null;
    this.statusBarOriginalNextSibling = null;
  }
  apply() {
    this.remove();
    if (!this.getSettings().disableNoteTabs)
      return;
    const rootEl = this.app.workspace.rootSplit.containerEl;
    const tabsEl = rootEl.querySelector(".workspace-tabs");
    if (!tabsEl)
      return;
    this.dragBar = document.createElement("div");
    this.dragBar.className = "minimalism-ui-drag-bar";
    const titleEl = document.createElement("span");
    titleEl.className = "minimalism-ui-drag-bar-title";
    this.dragBar.appendChild(titleEl);
    tabsEl.insertBefore(this.dragBar, tabsEl.firstChild);
    const updateTitle = () => {
      const activeFile = this.app.workspace.getActiveFile();
      titleEl.textContent = activeFile ? activeFile.basename : "";
    };
    updateTitle();
    this.titleHandler = updateTitle;
    this.app.workspace.on("active-leaf-change", updateTitle);
    this.renameHandler = (file) => {
      if (file === this.app.workspace.getActiveFile())
        updateTitle();
    };
    this.app.vault.on("rename", this.renameHandler);
    this.layoutHandler = () => {
      if (!this.dragBar || this.dragBar.isConnected)
        return;
      const rootEl2 = this.app.workspace.rootSplit.containerEl;
      const tabsEl2 = rootEl2.querySelector(".workspace-tabs");
      if (tabsEl2)
        tabsEl2.insertBefore(this.dragBar, tabsEl2.firstChild);
    };
    this.app.workspace.on("layout-change", this.layoutHandler);
    const statusBar = document.querySelector(".status-bar");
    if (statusBar) {
      this.statusBarOriginalParent = statusBar.parentElement;
      this.statusBarOriginalNextSibling = statusBar.nextElementSibling;
      this.dragBar.appendChild(statusBar);
    }
  }
  remove() {
    if (this.titleHandler) {
      this.app.workspace.off("active-leaf-change", this.titleHandler);
      this.titleHandler = null;
    }
    if (this.renameHandler) {
      this.app.vault.off("rename", this.renameHandler);
      this.renameHandler = null;
    }
    if (this.layoutHandler) {
      this.app.workspace.off("layout-change", this.layoutHandler);
      this.layoutHandler = null;
    }
    if (this.statusBarOriginalParent) {
      const statusBar = document.querySelector(".status-bar");
      if (statusBar) {
        if (this.statusBarOriginalNextSibling) {
          this.statusBarOriginalParent.insertBefore(statusBar, this.statusBarOriginalNextSibling);
        } else {
          this.statusBarOriginalParent.appendChild(statusBar);
        }
      }
      this.statusBarOriginalParent = null;
      this.statusBarOriginalNextSibling = null;
    }
    if (this.dragBar) {
      this.dragBar.remove();
      this.dragBar = null;
    }
  }
};

// src/SinglePageManager.ts
var import_obsidian = require("obsidian");
var SinglePageManager = class {
  constructor(app, getSettings, tabCache, getIsOpeningHomePage, setIsOpeningHomePage) {
    this.app = app;
    this.getSettings = getSettings;
    this.tabCache = tabCache;
    this.getIsOpeningHomePage = getIsOpeningHomePage;
    this.setIsOpeningHomePage = setIsOpeningHomePage;
    // ── Pin block ────────────────────────────────────────────────────────────
    this.pinBlockHandler = null;
    this.layoutChangeHandler = null;
    this.detachPatches = /* @__PURE__ */ new Map();
    // ── Home page ────────────────────────────────────────────────────────────
    this.homePageHandler = null;
  }
  // ── Pin block ─────────────────────────────────────────────────────────────
  /** Set up right-click pin blocking. Safe to call before layout is ready. */
  apply() {
    this.removePinBlock();
    if (!this.getSettings().disablePinTab)
      return;
    this.pinBlockHandler = (e) => {
      if (e.target.closest(".workspace-tab-header.tappable")) {
        e.stopImmediatePropagation();
        e.preventDefault();
      }
    };
    document.addEventListener("contextmenu", this.pinBlockHandler, true);
    this.patchSidebarLeafDetach();
    this.layoutChangeHandler = () => this.patchSidebarLeafDetach();
    this.app.workspace.on("layout-change", this.layoutChangeHandler);
  }
  patchSidebarLeafDetach() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (this.detachPatches.has(leaf))
        return;
      const leafEl = leaf.containerEl;
      if (!(leafEl == null ? void 0 : leafEl.closest(".workspace-split.mod-left-split")))
        return;
      const original = leaf.detach.bind(leaf);
      leaf.__minui_origDetach__ = original;
      leaf.detach = () => {
      };
      this.detachPatches.set(leaf, original);
    });
  }
  removePinBlock() {
    if (this.pinBlockHandler) {
      document.removeEventListener("contextmenu", this.pinBlockHandler, true);
      this.pinBlockHandler = null;
    }
    if (this.layoutChangeHandler) {
      this.app.workspace.off("layout-change", this.layoutChangeHandler);
      this.layoutChangeHandler = null;
    }
    for (const [leaf, original] of this.detachPatches) {
      leaf.detach = original;
      delete leaf.__minui_origDetach__;
    }
    this.detachPatches.clear();
  }
  // ── Home page ─────────────────────────────────────────────────────────────
  /** Register the file-open listener. Must be called after layout is ready. */
  applyHomePage() {
    this.removeHomePage();
    if (!this.getSettings().homePage)
      return;
    this.homePageHandler = (file) => {
      if (!file) {
        const active = this.app.workspace.getMostRecentLeaf();
        if (active && this.tabCache.hasPendingIntercept(active))
          return;
        void this.openHomePage();
      }
    };
    this.app.workspace.on("file-open", this.homePageHandler);
  }
  /** Open the home page in the current leaf. Must be called after layout is ready. */
  async openHomePage() {
    if (this.getIsOpeningHomePage())
      return;
    const path = this.getSettings().homePage;
    if (!path)
      return;
    if (document.querySelector(".modal-container"))
      return;
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile))
      return;
    this.setIsOpeningHomePage(true);
    try {
      const leaf = this.app.workspace.getLeaf(false);
      await leaf.openFile(file);
      this.tabCache.patchLeafHistory(leaf);
    } finally {
      this.setIsOpeningHomePage(false);
    }
  }
  removeHomePage() {
    if (this.homePageHandler) {
      this.app.workspace.off("file-open", this.homePageHandler);
      this.homePageHandler = null;
    }
  }
  // ── Cleanup ───────────────────────────────────────────────────────────────
  remove() {
    this.removePinBlock();
    this.removeHomePage();
  }
};

// src/SidebarLayoutManager.ts
var import_obsidian2 = require("obsidian");
var SidebarLayoutManager = class {
  constructor(app, getSettings) {
    this.app = app;
    this.getSettings = getSettings;
    // Guard against concurrent calls: each `apply()` awaits async ops, so a
    // second call arriving mid-flight would create duplicate leaves.
    this.isApplying = false;
  }
  // ── Public ────────────────────────────────────────────────────────────────
  async apply() {
    if (!this.getSettings().macSidebar)
      return;
    if (this.isApplying)
      return;
    this.isApplying = true;
    try {
      const { workspace } = this.app;
      const leftSplit = workspace.leftSplit;
      this.clearLeftSidebar();
      if (leftSplit == null ? void 0 : leftSplit.collapsed)
        leftSplit.expand();
      const outlineLeaf = workspace.getLeftLeaf(false);
      if (outlineLeaf) {
        await outlineLeaf.setViewState({ type: "outline", active: false });
      }
      const propsLeaf = workspace.getLeftLeaf(true);
      if (propsLeaf) {
        await propsLeaf.setViewState({ type: "file-properties", active: false });
      }
      await new Promise((resolve) => setTimeout(resolve, 100));
      const activeFile = workspace.getActiveFile();
      if (activeFile) {
        workspace.trigger("file-open", activeFile);
        await new Promise((resolve) => setTimeout(resolve, 50));
      }
      if (outlineLeaf && propsLeaf) {
        this.injectMetadataIntoOutline(outlineLeaf, propsLeaf);
      }
    } finally {
      this.isApplying = false;
    }
  }
  // ── Private ───────────────────────────────────────────────────────────────
  /**
   * Moves `.metadata-content` (direct child of `.metadata-container`) from
   * the Properties leaf into the Outline leaf's `.workspace-leaf-content`.
   * The now-empty Properties workspace-tabs shell is hidden.
   */
  injectMetadataIntoOutline(outlineLeaf, propsLeaf) {
    const outlineEl = outlineLeaf.containerEl;
    const propsEl = propsLeaf.containerEl;
    const metadataContent = propsEl.querySelector(
      ".metadata-container > .metadata-content"
    );
    const outlineLeafContent = outlineEl.querySelector(
      '.workspace-leaf-content[data-type="outline"]'
    );
    if (!metadataContent || !outlineLeafContent)
      return;
    outlineLeafContent.appendChild(metadataContent);
    const propsWorkspaceTabs = propsEl.closest(".workspace-tabs");
    if (propsWorkspaceTabs) {
      propsWorkspaceTabs.style.display = "none";
    }
  }
  // ── Public helpers ────────────────────────────────────────────────────────
  /**
   * Clears every leaf from the left sidebar using three complementary strategies:
   *
   *   A. Walk leftSplit's internal workspace-item tree directly.
   *      Works regardless of DOM state (collapsed sidebar, mid-rebuild, etc.).
   *
   *   B. DOM traversal via containerEl.closest('.mod-left-split').
   *      Catches leaves whose workspace-item tree position wasn't found in A
   *      (e.g. floating / detached DOM fragments that still reference a split).
   *
   *   C. Full iterateAllLeaves sweep for the outline type.
   *      Guards against leaves that survived A and B because their containerEl
   *      was missing or not yet attached to the document.
   *
   * Results from all three are de-duplicated via a Set before detaching.
   *
   * NOTE: SinglePageManager may patch leaf.detach() to a no-op when disablePinTab
   * is enabled. We bypass this by calling the original stored as __minui_origDetach__.
   */
  clearLeftSidebar() {
    const { workspace } = this.app;
    const all = /* @__PURE__ */ new Set();
    const leftSplit = workspace.leftSplit;
    for (const leaf of this.collectLeavesFromItem(leftSplit)) {
      all.add(leaf);
    }
    workspace.iterateAllLeaves((leaf) => {
      const el = leaf.containerEl;
      if (el == null ? void 0 : el.closest(".workspace-split.mod-left-split")) {
        all.add(leaf);
      }
    });
    for (const leaf of all) {
      try {
        this.forceDetach(leaf);
      } catch (e) {
      }
    }
    const stragglers = [];
    workspace.iterateAllLeaves((leaf) => {
      const type = leaf.getViewState().type;
      if (type === "outline")
        stragglers.push(leaf);
    });
    for (const leaf of stragglers) {
      try {
        this.forceDetach(leaf);
      } catch (e) {
      }
    }
  }
  /**
   * Detaches a leaf, bypassing SinglePageManager's pin-block patch if active.
   * SinglePageManager stores the original detach as __minui_origDetach__ on the leaf.
   */
  forceDetach(leaf) {
    const orig = leaf.__minui_origDetach__;
    if (orig) {
      orig();
    } else {
      leaf.detach();
    }
  }
  /**
   * Recursively collects all WorkspaceLeaf instances from a workspace item
   * (WorkspaceSplit / WorkspaceSidedock / WorkspaceTabs / WorkspaceLeaf).
   */
  collectLeavesFromItem(item) {
    if (!item || typeof item !== "object")
      return [];
    if (item instanceof import_obsidian2.WorkspaceLeaf)
      return [item];
    const children = item.children;
    if (!Array.isArray(children))
      return [];
    return children.flatMap((child) => this.collectLeavesFromItem(child));
  }
};

// src/SettingTab.ts
var import_obsidian3 = require("obsidian");
var FileSuggest = class extends import_obsidian3.AbstractInputSuggest {
  constructor() {
    super(...arguments);
    this.onPickCb = null;
  }
  onPick(cb) {
    this.onPickCb = cb;
    return this;
  }
  getSuggestions(query) {
    return this.app.vault.getMarkdownFiles().filter((f) => f.path.toLowerCase().includes(query.toLowerCase())).slice(0, 20);
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    var _a;
    this.setValue(file.path);
    (_a = this.onPickCb) == null ? void 0 : _a.call(this, file.path);
    this.close();
  }
};
var MinimalismUISettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("\u5916\u89C2\u8BBE\u7F6E").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u6781\u7B80\u4FA7\u8FB9\u680F").setDesc("\u4E3A\u5DE6\u4FA7\u8FB9\u680F\u5E94\u7528\u78E8\u7802\u73BB\u7483\u80CC\u666F\u4E0E\u5706\u89D2\u9AD8\u4EAE\uFF0C\u6253\u9020 macOS \u539F\u751F\u98CE\u683C\u3002").addToggle((t) => t.setValue(this.plugin.settings.macSidebar).onChange(async (v) => {
      this.plugin.settings.macSidebar = v;
      await this.plugin.saveSettings();
      this.plugin.applyBodyClasses();
      if (v)
        await this.plugin.applyMacSidebarLayout();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u6781\u7B80\u4FE1\u606F\u680F").setDesc("\u9690\u85CF\u5DE6\u4FA7\u5C5E\u6027\u680F\u7684\u64CD\u4F5C\u6309\u94AE\uFF0C\u4EE5\u53CA\u5927\u7EB2\u3001\u53CD\u5411\u94FE\u63A5\u9762\u677F\u4E2D\u7684\u641C\u7D22\u6846").addToggle((t) => t.setValue(this.plugin.settings.hideTabBar).onChange(async (v) => {
      this.plugin.settings.hideTabBar = v;
      this.plugin.settings.simplifyPanel = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u7B14\u8BB0\u6837\u5F0F\u4F18\u5316").setDesc("\u4FEE\u6539\u7B14\u8BB0\u90E8\u5206\u4E3B\u9898\u6837\u5F0F").addToggle((t) => t.setValue(this.plugin.settings.noteStyle).onChange(async (v) => {
      this.plugin.settings.noteStyle = v;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u4EA4\u4E92\u8BBE\u7F6E").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u7B14\u8BB0\u9996\u9875").setDesc("\u8BBE\u7F6E\u4E00\u4E2A\u7B14\u8BB0\u4F5C\u4E3A\u9996\u9875\u3002Obsidian \u542F\u52A8\u65F6\u81EA\u52A8\u6253\u5F00\uFF0C\u5173\u95ED\u6240\u6709\u6807\u7B7E\u540E\u81EA\u52A8\u8FD4\u56DE\u3002").addText((text) => {
      text.setPlaceholder("\u8F93\u5165\u7B14\u8BB0\u8DEF\u5F84\uFF0C\u4F8B\u5982\uFF1Asrc/Home.md").setValue(this.plugin.settings.homePage);
      new FileSuggest(this.app, text.inputEl).onPick((path) => {
        this.plugin.settings.homePage = path;
        void this.plugin.saveSettings();
      });
      text.inputEl.addEventListener("change", () => {
        this.plugin.settings.homePage = text.inputEl.value.trim();
        void this.plugin.saveSettings();
      });
    });
    const singlePageSetting = new import_obsidian3.Setting(containerEl).setName("\u5355\u9875\u6A21\u5F0F");
    singlePageSetting.settingEl.addClass("minimalism-ui-single-page-setting");
    singlePageSetting.addToggle((t) => t.setValue(this.plugin.settings.disableNoteTabs).onChange(async (v) => {
      this.plugin.settings.disableNoteTabs = v;
      this.plugin.settings.disablePinTab = v;
      this.plugin.settings.enableLeafCache = v;
      await this.plugin.saveSettings();
    }));
    singlePageSetting.descEl.createEl("span", { text: "1.\u9690\u85CF\u9876\u90E8\u6807\u7B7E\u680F\uFF0C\u6BCF\u6B21\u53EA\u5C55\u793A\u4E00\u7BC7\u7B14\u8BB0\u3002" });
    singlePageSetting.descEl.createEl("br");
    singlePageSetting.descEl.createEl("span", { text: "2.\u542F\u7528\u9875\u9762\u7F13\u5B58\uFF0C\u5728\u5185\u5B58\u4E2D\u4FDD\u7559\u6700\u8FD1\u8BBF\u95EE\u7684 10 \u4E2A\u9875\u9762" });
    singlePageSetting.descEl.createEl("br");
    singlePageSetting.descEl.createEl("span", { text: "3.\u7981\u7528 pin \u6807\u7B7E\u529F\u80FD\uFF0C\u907F\u514D\u591A\u4F59\u7684\u6807\u7B7E\u88AB\u56FA\u5B9A\u5728\u9876\u90E8\u3002" });
    singlePageSetting.descEl.createEl("br");
    new import_obsidian3.Setting(containerEl).setName("\u9875\u9762\u52A0\u8F7D\u52A8\u753B (beta)").setDesc("\u524D\u8FDB\u6216\u540E\u9000\u65F6\uFF0C\u4E3A\u76EE\u6807\u9875\u9762\u64AD\u653E\u6ED1\u5165\u52A8\u753B").addToggle((t) => t.setValue(this.plugin.settings.enableNavAnimation).onChange(async (v) => {
      this.plugin.settings.enableNavAnimation = v;
      await this.plugin.saveSettings();
    }));
  }
};

// main.ts
var MinimalismUIPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    // Shared flag between TabCacheManager and SinglePageManager.
    // TabCacheManager reads it to skip getLeaf interception while the home page
    // is opening; SinglePageManager writes it during openHomePage().
    this.isOpeningHomePage = false;
    this.outlineNavHandler = null;
    this.loadedFonts = [];
  }
  async onload() {
    await this.loadSettings();
    this.tabCache = new TabCacheManager(
      this.app,
      () => this.settings,
      () => this.isOpeningHomePage
    );
    this.dragBar = new DragBarManager(this.app, () => this.settings);
    this.sidebarLayout = new SidebarLayoutManager(this.app, () => this.settings);
    this.singlePage = new SinglePageManager(
      this.app,
      () => this.settings,
      this.tabCache,
      () => this.isOpeningHomePage,
      (v) => {
        this.isOpeningHomePage = v;
      }
    );
    await this.loadJetBrainsMono();
    this.applyBodyClasses();
    this.singlePage.apply();
    this.applyOutlineAnimation();
    this.tabCache.apply();
    this.app.workspace.onLayoutReady(() => {
      this.dragBar.apply();
      this.singlePage.applyHomePage();
      void this.singlePage.openHomePage();
      void this.sidebarLayout.apply();
    });
    this.addSettingTab(new MinimalismUISettingTab(this.app, this));
  }
  onunload() {
    document.body.classList.remove(
      "minimalism-ui-mac-sidebar",
      "minimalism-ui-hide-tab-bar",
      "minimalism-ui-disable-pin",
      "minimalism-ui-simplify-panel",
      "minimalism-ui-disable-note-tabs",
      "minimalism-ui-note-style"
    );
    for (const font of this.loadedFonts)
      document.fonts.delete(font);
    this.loadedFonts = [];
    this.singlePage.remove();
    this.tabCache.remove();
    this.dragBar.remove();
    this.removeOutlineAnimation();
  }
  // ─── Sidebar Layout ───────────────────────────────────────────────────────
  async applyMacSidebarLayout() {
    await this.sidebarLayout.apply();
  }
  // ─── Body Classes ─────────────────────────────────────────────────────────
  applyBodyClasses() {
    const cls = document.body.classList;
    cls.toggle("minimalism-ui-mac-sidebar", this.settings.macSidebar);
    cls.toggle("minimalism-ui-hide-tab-bar", this.settings.hideTabBar);
    cls.toggle("minimalism-ui-disable-pin", this.settings.disablePinTab);
    cls.toggle("minimalism-ui-simplify-panel", this.settings.simplifyPanel);
    cls.toggle("minimalism-ui-disable-note-tabs", this.settings.disableNoteTabs);
    cls.toggle("minimalism-ui-note-style", this.settings.noteStyle);
  }
  // ─── Settings ─────────────────────────────────────────────────────────────
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applyBodyClasses();
    this.singlePage.apply();
    this.tabCache.apply();
    this.dragBar.apply();
    this.singlePage.applyHomePage();
    this.applyOutlineAnimation();
    if (this.settings.macSidebar)
      void this.sidebarLayout.apply();
  }
  // ─── Outline Animation ────────────────────────────────────────────────────
  applyOutlineAnimation() {
    this.removeOutlineAnimation();
    if (!this.settings.noteStyle)
      return;
    this.outlineNavHandler = (e) => {
      const item = e.target.closest(".tree-item-inner");
      if (!(item == null ? void 0 : item.closest('[data-type="outline"]')))
        return;
      setTimeout(() => this.flashCurrentHeading(), 50);
    };
    document.addEventListener("click", this.outlineNavHandler, true);
  }
  removeOutlineAnimation() {
    if (this.outlineNavHandler) {
      document.removeEventListener("click", this.outlineNavHandler, true);
      this.outlineNavHandler = null;
    }
  }
  flashCurrentHeading() {
    const leaf = this.app.workspace.getMostRecentLeaf();
    if (!leaf)
      return;
    const scrollEl = leaf.view.containerEl.querySelector(".markdown-preview-view");
    if (!scrollEl)
      return;
    const containerRect = scrollEl.getBoundingClientRect();
    const headings = scrollEl.querySelectorAll("h1, h2, h3, h4, h5, h6");
    let target = null;
    let minDist = Infinity;
    for (const h of Array.from(headings)) {
      const dist = Math.abs(h.getBoundingClientRect().top - containerRect.top);
      if (dist < minDist) {
        minDist = dist;
        target = h;
      }
    }
    if (target) {
      const el = target;
      el.classList.add("minimalism-ui-heading-flash");
      el.addEventListener("animationend", () => el.classList.remove("minimalism-ui-heading-flash"), { once: true });
    }
  }
  // ─── Fonts ────────────────────────────────────────────────────────────────
  fontPath(filename) {
    const adapter = this.app.vault.adapter;
    return adapter.getResourcePath(`${this.manifest.dir}/fonts/${filename}`);
  }
  async loadFontFace(family, descriptors) {
    const { file, ...desc } = descriptors;
    const face = new FontFace(family, `url('${this.fontPath(file)}')`, desc);
    try {
      await face.load();
      document.fonts.add(face);
      this.loadedFonts.push(face);
    } catch (e) {
    }
  }
  async loadJetBrainsMono() {
    const digitsRange = "U+002D, U+002E, U+0030-0039";
    await Promise.all([
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Regular.ttf", style: "normal", weight: "400" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Italic.ttf", style: "italic", weight: "400" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Medium.ttf", style: "normal", weight: "500" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-MediumItalic.ttf", style: "italic", weight: "500" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-Bold.ttf", style: "normal", weight: "700" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-BoldItalic.ttf", style: "italic", weight: "700" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-ExtraBold.ttf", style: "normal", weight: "900" }),
      this.loadFontFace("JetBrains Mono", { file: "JetBrainsMonoNL-ExtraBoldItalic.ttf", style: "italic", weight: "900" }),
      // 数字专用字族：只覆盖数字 unicode 范围，用于正文混排
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-Regular.ttf", style: "normal", weight: "400", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-Italic.ttf", style: "italic", weight: "400", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-Medium.ttf", style: "normal", weight: "500", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-MediumItalic.ttf", style: "italic", weight: "500", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-Bold.ttf", style: "normal", weight: "700", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-BoldItalic.ttf", style: "italic", weight: "700", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-ExtraBold.ttf", style: "normal", weight: "900", unicodeRange: digitsRange }),
      this.loadFontFace("JetBrains Mono Digits", { file: "JetBrainsMonoNL-ExtraBoldItalic.ttf", style: "italic", weight: "900", unicodeRange: digitsRange })
    ]);
  }
};
